/*
 * Please so not edit this file by hand!
 * This file was automatically generated by: nddsgen
 */

#include <rpc/types.h>
#include <rpc/xdr.h>
#include "info.h"


bool_t
xdr_infoStruct(XDR *xdrs, infoStruct *objp)
{
	if (!xdr_vector(xdrs, (char *)objp->message, 1000, sizeof(char), xdr_char)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->source, 100, sizeof(char), xdr_char)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->verbosity)) {
		return (FALSE);
	}
	if (!xdr_u_int(xdrs, &objp->msecs)) {
		return (FALSE);
	}
	if (!xdr_u_int(xdrs, &objp->week)) {
		return (FALSE);
	}
	return (TRUE);
}


