/*
 * Please so not edit this file by hand!
 * This file was automatically generated by: nddsgen
 */

#include <rpc/types.h>
#include <rpc/xdr.h>
#include "panoramicImageReq.h"


bool_t
xdr_panoramicImageReqStruct(XDR *xdrs, panoramicImageReqStruct *objp)
{
	if (!xdr_char(xdrs, &objp->data)) {
		return (FALSE);
	}
	return (TRUE);
}


