module camera
{
	struct Cluster_Encoder {
	  long	Image_mean[3216];	// 18 | none | Mean of image pixels (1/amp)
	  long	Image_SD[3216];	// 18 | none | StDev of image pixels (1/amp)
	  long	Overscan_mean[3216];	// 18 | none | Mean of overscan pixels (1/amp)
	  long	Overscan_SD[3216];	// 18 | none | StDev of overscan pixels (1/amp)
	  long	PSF[9648];	// 18 | none | Image PSF (3/amp)
	};
	#pragma keylist Cluster_Encoder
};
