module camera
{
	struct SDS_TCM {
	  long	Timing_parameter[10];	// 18 | none | Timing parameters[
	  unsigned short	REB_ID;	// none | | Raft Electronics Board ID
	};
	#pragma keylist SDS_TCM
	struct SDS_status {
	  long	flag[20];	// 18 | none | Error flags[
	  unsigned short	REB_ID;	// none | | Raft Electronics Board ID
	};
	#pragma keylist SDS_status
};
