module system
{
	struct system {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  long	health[500];
	  long	power[500];
	  long	thermal[500];
	};
	#pragma keylist system
	struct system_accesscontrol {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  string<128>	subssystem;
	  string<128>	device;
	  string<500>	bystation;
	  string<500>	byoperator;
	  string<500>	bypolicy;
	};
	#pragma keylist system_accesscontrol
	struct system_configuration {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  string<128>	subssystem;
	  string<128>	device;
	  long	stationid;
	};
	#pragma keylist system_configuration
	struct system_networking {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  string<128>	subsystem;
	  string<32>	mac;
	  long	ip[4];
	  long	rx[6];
	  long	tx[6];
	};
	#pragma keylist system_networking
	struct Command_history {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  string<32>	Command;
	  float	Data[16];
	};
	#pragma keylist Command_history
	struct Computer_status {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  long	Raw[16];
	  float	Calibrated[32];
	};
	#pragma keylist Computer_status
	struct Hardware_revision_history {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  string<32>	Part;
	  string<32>	Reason;
	  long	Version[3];
	};
	#pragma keylist Hardware_revision_history
	struct Software_revision_history {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  string<32>	PackageName;
	  string<32>	Notes;
	  long	Version[3];
	};
	#pragma keylist Software_revision_history
};
