module rotator {
	struct Electrical {
	  long	error[16];
	  short	status[16];
	  long	voltage[16];
	};
	#pragma keylist Electrical
	struct LimitSensors {
	  short	liftoff[18];
	  short	limit[18];
	};
	#pragma keylist LimitSensors
	struct Position {
	  float	Calibrated[32];
	  long	Raw[16];
	};
	#pragma keylist Position
	struct TC {
	  float	error[16];
	  float	setpoint[16];
	  short	status[16];
	  float	temperature[16];
	};
	#pragma keylist TC
	struct command_configureAcceleration {
	  string<32>	device;
	  string<32>	property;
	  string<32>	action;
	  string<32>	value;
	  double	amin;
	  double	amax;
	};
	#pragma keylist command_configureAcceleration
	struct command_configureVelocity {
	  string<32>	device;
	  string<32>	property;
	  string<32>	action;
	  string<32>	value;
	  double	vmin;
	  double	vmax;
	};
	#pragma keylist command_configureVelocity
	struct command_move {
	  string<32>	device;
	  string<32>	property;
	  string<32>	action;
	  string<32>	value;
	  double	angle;
	};
	#pragma keylist command_move
	struct logevent_interlock {
	  long	priority;
	  string	detail;
	};
	#pragma keylist logevent_interlock
	struct logevent_limit {
	  long	priority;
	  string	limit;
	  string	type;
	};
	#pragma keylist logevent_limit
	struct logevent_tempError {
	  long	priority;
	  string	device;
	  long	severity;
	};
	#pragma keylist logevent_tempError
	struct command
	{
      string<32>	device;
      string<32>	property;
      string<32>	action;
      string<32>	value;
      string<128>	modifiers;
	};
	#pragma keylist command
	struct ackcmd
	{
      long 		ack;
      long 		error;
      string<32>	result;
	};
	#pragma keylist ackcmd
	struct logevent
	{
      string<128>	message;
	};
	#pragma keylist logevent
};

