module tcs {
	struct AOCS {
	  string	result;
	};
	#pragma keylist AOCS
	struct WEP {
	  string<256>    basis_set_name;
	  long	number_of_terms;
	  double	z_arr1[64];
	  double	z_arr2[64];
	  double	z_arr3[64];
	  double	z_arr4[64];
	};
	#pragma keylist WEP
	struct ZEMAX {
	  string	bg_algorithm;
	  double	exposure;
	  long	iterations;
	};
	#pragma keylist ZEMAX
	struct command_wfpCalculate {
	  string<32>	device;
	  string<32>	property;
	  string<32>	action;
	  string<32>	value;
	  string<64>	uid;
	};
	#pragma keylist command_wfpCalculate
	struct command_wfpSimulate {
	  string<32>	device;
	  string<32>	property;
	  string<32>	action;
	  string<32>	value;
	  string<64>	uid;
	  double	z_arr[18];
	};
	#pragma keylist command_wfpSimulate
	struct kernel {
	  float	dec;
	  float	epoc;
	  float	equinox;
	  float	parallax;
	  float	pmDec;
	  float	pmRA;
	  float	ra;
	  float	rv;
	};
	#pragma keylist kernel
	struct logevent_wfpDataReady {
	  long	priority;
	  string<256>	images_location_URI;
	  string<64>	images_match_URI;
	};
	#pragma keylist logevent_wfpDataReady
	struct logevent_zemaxError {
	  long	priority;
	  string<128>	details;
	};
	#pragma keylist logevent_zemaxError
	struct command
	{
      string<32>	device;
      string<32>	property;
      string<32>	action;
      string<32>	value;
      string<128>	modifiers;
	};
	#pragma keylist command
	struct ackcmd
	{
      long 		ack;
      long 		error;
      string<32>	result;
	};
	#pragma keylist ackcmd
	struct logevent
	{
      string<128>	message;
	};
	#pragma keylist logevent
};

