module dm {
	struct alert {
	  double	summary_data_quality_parameters[32];
	};
	#pragma keylist alert
	struct alert_dq {
	  double	summary_data_quality_parameters[32];
	};
	#pragma keylist alert_dq
	struct alert_psf {
	  double	psf_wcs_last_visit[32];
	};
	#pragma keylist alert_psf
	struct alert_summary {
	  long	alerts_sent;
	  long	available_workers;
	  long	latency_readout_to_last_alert;
	};
	#pragma keylist alert_summary
	struct available_replicators_distributors {
	  long	machine_count;
	};
	#pragma keylist available_replicators_distributors
	struct efd_slave_replication_state {
	  long	replication_state;
	};
	#pragma keylist efd_slave_replication_state
	struct international_network_status {
	  long	link_usage;
	  long	link_utilization;
	  long	link_capacity;
	  long	link_latency;
	};
	#pragma keylist international_network_status
	struct logevent_dmPublished {
	  long	priority;
	  long	visit_identifier;
	  long	alert_count;
	};
	#pragma keylist logevent_dmPublished
	struct logevent_dmToArchive {
	  long	priority;
	  long	image_id;
	};
	#pragma keylist logevent_dmToArchive
	struct logevent_dmToBase {
	  long	priority;
	  long	image_id;
	};
	#pragma keylist logevent_dmToBase
	struct logevent_image_archived_archive {
	  long	image_id;
	};
	#pragma keylist logevent_image_archived_archive
	struct logevent_image_archived_base {
	  long	image_id;
	};
	#pragma keylist logevent_image_archived_base
	struct logevent_processed_and_published {
	  long	visit_identifier;
	  long	alert_count;
	};
	#pragma keylist logevent_processed_and_published
	struct raft_images_sent_current {
	  long	current_mode_image_count;
	  long	operations_image_count;
	};
	#pragma keylist raft_images_sent_current
	struct successfully_archived {
	  long	focal_plane_current_image_count;
	  long	focal_plane_operations_image_count;
	  long	last_focal_plane_image_id;
	};
	#pragma keylist successfully_archived
	struct summit_to_base_network_status {
	  long	link_usage;
	  long	link_utilization;
	  long	link_capacity;
	  long	link_latency;
	};
	#pragma keylist summit_to_base_network_status
	struct command
	{
      string<32>	device;
      string<32>	property;
      string<32>	action;
      string<32>	value;
      string<128>	modifiers;
	};
	#pragma keylist command
	struct ackcmd
	{
      long 		ack;
      long 		error;
      string<32>	result;
	};
	#pragma keylist ackcmd
	struct logevent
	{
      string<128>	message;
	};
	#pragma keylist logevent
};

