#!/bin/sh

NDDSHOME=$(pwd)/../ndds.4.2e
export NDDSHOME
LD_LIBRARY_PATH=${NDDSHOME}/lib/i86Linux2.6gcc3.4.3:$(pwd)/../lsstsal.1.0/lib
export LD_LIBRARY_PATH
PATH=${PATH}:${NDDSHOME}/scripts
export PATH
make $@


