   struct logevent_error {
      string<32> private_revCode; //private
      double private_sndStamp;    //private
      double private_rcvStamp;    //private
      long private_seqNum;        //private
      long private_origin;        //private
      long private_host;          //private
      short hexapodID;
   };
   #pragma keylist logevent_error hexapodID
   struct logevent_interlock {
      string<32> private_revCode; //private
      double private_sndStamp;    //private
      double private_rcvStamp;    //private
      long private_seqNum;        //private
      long private_origin;        //private
      long private_host;          //private
      short hexapodID;
      string  detail;
      string  detail;
   };
   #pragma keylist logevent_interlock hexapodID
   struct logevent_limit {
      string<32> private_revCode; //private
      double private_sndStamp;    //private
      double private_rcvStamp;    //private
      long private_seqNum;        //private
      long private_origin;        //private
      long private_host;          //private
      short hexapodID;
      string	axis;
      string	limit;
      string	type;
      string	axis;
      string	limit;
      string	type;
   };
   #pragma keylist logevent_limit hexapodID
   struct logevent_slewOK {
      string<32> private_revCode; //private
      double private_sndStamp;    //private
      double private_rcvStamp;    //private
      long private_seqNum;        //private
      long private_origin;        //private
      long private_host;          //private
      short hexapodID;
   };
   #pragma keylist logevent_slewOK hexapodID
   struct logevent_temp {
      string<32> private_revCode; //private
      double private_sndStamp;    //private
      double private_rcvStamp;    //private
      long private_seqNum;        //private
      long private_origin;        //private
      long private_host;          //private
      short hexapodID;
      string  axis;
      string  device;
      long    severity;
      string  axis;
      string  device;
      long    severity;
   };
   #pragma keylist logevent_temp hexapodID
   struct logevent_trackLost {
      string<32> private_revCode; //private
      double private_sndStamp;    //private
      double private_rcvStamp;    //private
      long private_seqNum;        //private
      long private_origin;        //private
      long private_host;          //private
      short hexapodID;
   };
   #pragma keylist logevent_trackLost hexapodID
   struct logevent_tracking {
      string<32> private_revCode; //private
      double private_sndStamp;    //private
      double private_rcvStamp;    //private
      long private_seqNum;        //private
      long private_origin;        //private
      long private_host;          //private
      short hexapodID;
   };
   #pragma keylist logevent_tracking hexapodID
