set OSPL_VERSION 6.4.1
set OSPL_BASE $env(LSST_SDK_INSTALL)/OpenSpliceDDS/V$OSPL_VERSION
set LVERSION x86_64.linux
set OSPL_HDE $OSPL_BASE/HDE/$LVERSION
set DDSGEN "$OSPL_HDE/bin/idlpp -I $OSPL_HDE/etc/idl"


