#!/usr/bin/tclsh

set skey [clock seconds]
set froot /opt/upload/$skey
exec mkdir -p $froot
cd $froot
exec mkdir -p idl-templates/validated/sal .
exec ln -s /opt/test/html .
exec ln -s /opt/test/sql .
exec ln -s /opt/test/xml .
set finput $argv
set ftype [file extension $finput]


if { $ftype == ".gz" } {
   puts stdout "Unpacking archive $finput"
   exec gzip -d ../$finput
   exec tar xf ../[file rootname $finput].tar
}
if { $ftype == ".bz2" } {
   puts stdout "Unpacking archive $finput"
   exec bzip2 -d ../$finput
   exec tar xf ../[file rootname $finput].tar
}
if { $ftype == ".tgz" } {
   puts stdout "Unpacking archive $finput"
   exec tar xzf ../$finput
}
if { $ftype == ".zip" } {
   puts stdout "Unpacking archive $finput"
   exec unzip -x ../$finput
}

set all [glob *]
set subsys ""
foreach i $all {
 if { [file isdirectory $i] == 0 } {
puts stdout "processing $i"
   set ftype [file extension $i]
   if { $ftype == ".idl" } {
      if { $subsys == ""} {set subsys [lindex [split $i "_"] 0]}
      exec runsalgenerator $froot $i validate
   }
   if { $ftype == ".xml" } {
      if { $subsys == ""} {set subsys [lindex [split $i "_"] 0]}
      exec runsalgenerator $froot $i parseXML
puts stdout "Done parsing"
      exec runsalgenerator $froot [set subsys]_*.idl validate
   }
 }
}
if { [file exists command_list_[set subsys]] == 0 } {
   exec cp /opt/lsstsal/scripts/cmdevt-templates/command_list_[set subsys] .
}
exec runsalgenerator $froot parseCommandList $subsys

if { [file exists event_list_[set subsys]] == 0 } {
   exec cp /opt/lsstsal/scripts/cmdevt-templates/event_list_[set subsys] .
}
exec runsalgenerator $froot parseEventList $subsys

exec runsalgenerator $froot [set subsys]_*.idl html



