/*
 * Please so not edit this file by hand!
 * This file was automatically generated by: nddsgen
 */

#include <rpc/types.h>
#include <rpc/xdr.h>
#include "dbIDListReply.h"


bool_t
xdr_dbIDListReplyStruct(XDR *xdrs, dbIDListReplyStruct *objp)
{
	if (!xdr_int(xdrs, &objp->replyStatus)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->replyDestination)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->targetIDs, 1000, sizeof(int), xdr_int)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->numTargetIDs)) {
		return (FALSE);
	}
	return (TRUE);
}


