/*
 * Please so not edit this file by hand!
 * This file was automatically generated by: nddsgen
 */

#include <rpc/types.h>
#include <rpc/xdr.h>
#include "rtChassisConfig.h"


bool_t
xdr_rtChassisConfigStruct(XDR *xdrs, rtChassisConfigStruct *objp)
{
	if (!xdr_char(xdrs, &objp->rtChassisConfigFlag)) {
		return (FALSE);
	}
	return (TRUE);
}


