/*
 * Please so not edit this file by hand!
 * This file was automatically generated by: nddsgen
 */

#include <rpc/types.h>
#include <rpc/xdr.h>
#include "rtEmergencySignals.h"


bool_t
xdr_rtEmergencySignalsStruct(XDR *xdrs, rtEmergencySignalsStruct *objp)
{
	if (!xdr_char(xdrs, &objp->rtEStop)) {
		return (FALSE);
	}
	if (!xdr_char(xdrs, &objp->rtKillSwitch)) {
		return (FALSE);
	}
	return (TRUE);
}


