/*
 * Please so not edit this file by hand!
 * This file was automatically generated by: nddsgen
 */

#include <rpc/types.h>
#include <rpc/xdr.h>
#include "rtSetServoParams.h"


bool_t
xdr_rtSetServoParamsStruct(XDR *xdrs, rtSetServoParamsStruct *objp)
{
	if (!xdr_int(xdrs, &objp->servoId)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->gain, 3, sizeof(int), xdr_int)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->integrationLimit)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->errorLimit)) {
		return (FALSE);
	}
	return (TRUE);
}


