/*
 * Please so not edit this file by hand!
 * This file was automatically generated by: nddsgen
 */

#include <rpc/types.h>
#include <rpc/xdr.h>
#include "rtSetActuator.h"


bool_t
xdr_rtSetActuatorStruct(XDR *xdrs, rtSetActuatorStruct *objp)
{
	if (!xdr_int(xdrs, &objp->actuatorId)) {
		return (FALSE);
	}
	if (!xdr_float(xdrs, &objp->position)) {
		return (FALSE);
	}
	if (!xdr_float(xdrs, &objp->velocity)) {
		return (FALSE);
	}
	if (!xdr_float(xdrs, &objp->accel)) {
		return (FALSE);
	}
	return (TRUE);
}


