/*
 * Please so not edit this file by hand!
 * This file was automatically generated by: nddsgen
 */

#include <rpc/types.h>
#include <rpc/xdr.h>
#include "rtSetParamFloat.h"


bool_t
xdr_rtSetParamFloatStruct(XDR *xdrs, rtSetParamFloatStruct *objp)
{
	if (!xdr_int(xdrs, &objp->paramId)) {
		return (FALSE);
	}
	if (!xdr_float(xdrs, &objp->value)) {
		return (FALSE);
	}
	return (TRUE);
}


