/*
 * Please so not edit this file by hand!
 * This file was automatically generated by: nddsgen
 */

#include <rpc/types.h>
#include <rpc/xdr.h>
#include "mpSensorStatus.h"


bool_t
xdr_mpSensorStatusStruct(XDR *xdrs, mpSensorStatusStruct *objp)
{
	if (!xdr_int(xdrs, &objp->sensorID)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->sensorStatus)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->extendedSensorStatus)) {
		return (FALSE);
	}
	if (!xdr_float(xdrs, &objp->timeCost)) {
		return (FALSE);
	}
	if (!xdr_float(xdrs, &objp->powerCost)) {
		return (FALSE);
	}
	return (TRUE);
}


