/*
 * Please so not edit this file by hand!
 * This file was automatically generated by: nddsgen
 */

#include <rpc/types.h>
#include <rpc/xdr.h>
#include "navEnable.h"


bool_t
xdr_navEnableStruct(XDR *xdrs, navEnableStruct *objp)
{
	if (!xdr_char(xdrs, &objp->navEnableFlag)) {
		return (FALSE);
	}
	return (TRUE);
}


