/*
 * Please so not edit this file by hand!
 * This file was automatically generated by: nddsgen
 */

#include <rpc/types.h>
#include <rpc/xdr.h>
#include "navPath.h"


bool_t
xdr_navPathStruct(XDR *xdrs, navPathStruct *objp)
{
	if (!xdr_int(xdrs, &objp->number)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->waypoint, 10, sizeof(float), xdr_float)) {
		return (FALSE);
	}
	return (TRUE);
}


