/*
 * Please so not edit this file by hand!
 * This file was automatically generated by: nddsgen
 */

#include <rpc/types.h>
#include <rpc/xdr.h>
#include "navReset.h"


bool_t
xdr_navResetStruct(XDR *xdrs, navResetStruct *objp)
{
	if (!xdr_char(xdrs, &objp->navResetFlag)) {
		return (FALSE);
	}
	return (TRUE);
}


