struct auxscope_TC {
  string<32> private_revCode; //private
  double private_sndStamp; //private
  double private_rcvStamp; //private
  long private_seqNum; //private
  long private_origin; //private
  long Raw[16];
  float Calibrated[16];
};
