struct camera_GAS {
  long	FPGACheckSum[2];	// 2.31E-05 | none | FPGA Configuration checksum (2/CCD) | none | Corner rafts | 8 | 8  | 32 
  float	Board_current[4];	// 0.054 | Volt | Electronics board currents (4/board) | none | Corner rafts | 16 | 37,362  | 149,449 
  long	CABAC_MUX[4];		// 0.054 | none | CABAC/ASPIC V &amp; T  (2 at a time, MUXed) | none | Corner rafts | 16 | 37,362  | 149,449 
  short	CCD_ID;			// 2.31E-05 | none | CCD ID ( ITL only) | none | Corner rafts | 4 | 4  | 8 
  short	Board_ID;		// 2.31E-05 | none | Board ID | none | Corner rafts | 4 | 4  | 8 
  float	CCD_temp;		// 0.054 | Kelvin | CCD temperatures | none | Corner rafts | 4 | 9,341  | 37,362 
  float	Board_temp[12];		// 0.054 | Kelvin | Board temps | none | Corner rafts | 48 | 112,086  | 448,346 
  float	Board_voltage[4];	// 0.054 | Volt | Electronics board voltages (4/board) | none | Corner rafts | 16 | 37,362  | 149,449 
  unsigned short REB_ID;	// 0.054 | none | Raft Electronics Board ID | none | Cryostat
};
#pragma keylist camera_GAS
