struct camera_Filter {
  long	Loader_telemetry;	// tbd | ?? | Loader | none | none | ?? |  | 
  unsigned short	REB_ID;	// 0.054 | none | Raft Electronics Board ID | none | Cryostat
};
#pragma keylist camera_Filter 
