struct camera_Purge_current {
  string<32> private_revCode;  //private
  double     private_sndStamp; //private
  double     private_rcvStamp; //private
  long       private_seqNum;   //private
  long       private_origin;   //private
  float	Heater_current;	// 0.017 | Amp | Heater settings |  | Camera body | ?? | ?? | ??
  float	Heaters;	// 0.017 | Amp | Heaters |  | Camera body | ?? | ?? | ??
};
#pragma keylist camera_Purge_current 
