struct camera_PCMS {
  short	FPGA_Status;		// 0.054 | none | FPGA Status | none | Utility trunk | 75 | 175,135  | 350,270 
  short	Low_Status;		// 0.054 | none | Low Status | none | Utility trunk | 75 | 175,135  | 350,270 
  short	Clock_Status;		// 0.054 | none | Clock Status | none | Utility trunk | 75 | 175,135  | 350,270 
  short	OD_Status;		// 0.054 | none | OD Status | none | Utility trunk | 75 | 175,135  | 350,270 
  short	Bias_Status;		// 0.054 | none | Bias Status | none | Utility trunk | 75 | 175,135  | 350,270 
  float	FPGA_voltage;		// 0.054 | none | FPGA voltage | none | Utility trunk | 75 | 175,135  | 700,541 
  float	Low_voltage;		// 0.054 | none | Low voltage | none | Utility trunk | 75 | 175,135  | 700,541 
  float	Clock_voltage;		// 0.054 | none | Clock voltage | none | Utility trunk | 75 | 175,135  | 700,541 
  float	OD_voltage;		// 0.054 | none | OD voltage | none | Utility trunk | 75 | 175,135  | 700,541 
  float	Bias_voltage;		// 0.054 | none | Bias voltage | none | Utility trunk | 75 | 175,135  | 700,541 
  unsigned short REB_ID;	// 0.054 | none | Raft Electronics Board ID | none | Cryostat
};
#pragma keylist camera_PCMS
