struct camera_GAS {
  float	CCD_temp;		// 0.054 | Kelvin | CCD temperatures | none | Corner rafts | 4 | 9,341  | 37,362 
  float	Board_temp[12];		// 0.054 | Kelvin | Board temps | none | Corner rafts | 48 | 112,086  | 448,346 
  float	Board_voltage[4];	// 0.054 | Volt | Electronics board voltages (4/board) | none | Corner rafts | 16 | 37,362  | 149,449 
  unsigned short REB_ID;	// 0.054 | none | Raft Electronics Board ID | none | Cryostat
};
#pragma keylist camera_GAS
