struct camera_Cold {
  float	Ion_pump[4];			// 0.010 | Amp | Ion pump current (3 cryostat, 1 heat exch) | none | Utility trunk | 4 | 1,728  | 6,912 
  float	Heater_current[6];		// 0.010 | Amp | Coldplate heater currents | none | Cryostat | 6 | 2,592  | 5,184 
  float	Intake_flow[6];			// 0.010 | lps | Compressor intake  flow | none | Utility room | 6 | 2,592  | 10,368 
  float	Compressor_load[6];		// 0.010 | Watts | Compressor electrical load | none | Utility room | 6 | 2,592  | 10,368 
  float	Intake_pressure[6];		// 0.010 | Pa | Compressor intake  pressure | none | Utility room | 6 | 2,592  | 10,368 
  float	Pre_expansion_pressure[6];	// 0.010 | Pa | Pre-expansion C4 pressure | none | Cryostat or utility trunk | 6 | 2,592  | 10,368 
  float	Post_expansion_pressure[6];	// 0.010 | Pa | Post-evaporator pressure | none | Cryostat or utility trunk | 6 | 2,592  | 10,368 
  float	Compressor_speed[6];		// 0.010 | Hz | Compressor speed | none | Utility room | 6 | 2,592  | 10,368 
  float	Dischaarge_pressure[6];		// 0.010 | Pa | Compressor discharge  pressure | none | Utility room | 6 | 2,592  | 10,368 
  float	Discharge_temp[6];		// 0.010 | Celsius | Compressor discharge  temperature | none | Utility room | 6 | 2,592  | 10,368 
  short	Valve_status[6];		// 0.000 | none | Vacuum valve status published on change | none | Utility trunk | 6 | 43  | 86 
  short	Mech_pump[4];			// 0.010 | none | Status (2 cryostat, 2 heat exch) | none | Utility trunk | 4 | 1,728  | 6,912 
  long	RGA[10];			// 0.010 | ?? | Two RGAs, 5 gasses each | none | Cryostat | 10 | ??  | ?? 
  short	Flow_interlock[6];		// 0.010 | none | Compressor water flow interlock | none | Utility room | 6 | 2,592  | 5,184 
  float	UtilityRoom_temperature;	// 0.010 | Celsius | Temperatures in utility room (8) | none | Utility room | 8 | 3,456  | 13,824 
  float	Intake_temp[6];			// 0.010 | Celsius | Compressor intake temperature | none | Utility room | 6 | 2,592  | 10,368 
  float	Pre_expansion_temp[6];		// 0.010 | Celsius | Pre-expansion C4 temperature | none | Cryostat or utility trunk | 6 | 2,592  | 10,368 
  float	Post_expansion_temp[6];		// 0.010 | Celsius | Post-evaporator temperature | none | Cryostat or utility trunk | 6 | 2,592  | 10,368 
  float	Return_temp[6];			// 0.010 | Celsius | Return line temperature | none | Cryostat or utility trunk | 6 | 2,592  | 10,368 
  float	Vacuum_gauge[5];		// 0.010 | Pa | 3 for cryostat, 2 for heat exchangers | none | Utility trunk | 5 | 2,160  | 8,640 
  float	Heater_voltage[6];		// 0.010 | Volt | Coldplate heater voltages | none | Cryostat | 6 | 2,592  | 5,184 
};
#pragma keylist camera_Cold 
