struct camera_SDS {
  long	flag[20];		// 0.054 | none | Error flags[ | none | Science and corner rafts | 1260 | 2,942,270  | 11,769,081 
  long	Timing_parameter[10];	// 0.054 | none | Timing parameters[ | none | Science and corner rafts | 630 | 1,471,135  | 5,884,541 
  unsigned short REB_ID;	// 0.054 | none | Raft Electronics Board ID | none | Cryostat
};
#pragma keylist camera_SDS
