struct dm_derived_dataquality {
  string<32> private_revCode; //private
  double private_sndStamp; //private
  double private_rcvStamp; //private
  long private_seqNum; //private
  long private_origin; //private
  double metric1[200];
  double metric2[200];
  double metric3[200];
  double metric4[200];
  double metric5[200];
  double metric6[200];
  double summary[100];
};
