struct dome_Application {
  float azTarget;
  float azPosition;
  float azError;
  float elevTarget;
  float elevPosition;
  float elevError;
  float scrTarget;
  float scrPosition;
  float scrError;
  float lvTarget[72];
  float lvPosition[72];
  float lvError[72];
};
