struct hexapod_command {
  string<32> private_revCode; //private
  double private_sndStamp; //private
  double private_rcvStamp; //private
  long private_seqNum; //private
  long private_origin; //private
  long cmdID;
  string<16>	device;
  string<16>	operation;
  string<16>	value;
  string<128>	modifiers;
};
