struct m1m3_Actuators {
  long setpoint[120];
  long position[120];
  long error[120];
  long status[120];
  float cyltemp[120];
  float envtemp[120];
  float lvdtcorr[120];
  float pressure[120];
};
