struct m2_Application {
  string<32> private_revCode; //private
  double private_sndStamp; //private
  double private_rcvStamp; //private
  long private_seqNum; //private
  long private_origin; //private
  float Demand[2];
  float Position[2];
  float Error[2];
};
