struct tcs_kernel_PointingLog {
  float Ra;
  float Dec;
  float Wavel;
  float Roll;
  float Pitch;
  float Casspa;
  float Xr;
  float Yr;
  float Fl;
  float Temp;
  float Press;
  float Humid;
  float Tlr;
  float Rcorr;
  float Aux[3];
  long Marked;
};
