struct tcs_kernel_Target {
  float t0;
  float az;
  float el;
  float azdot;
  float eldot;
  float Wavel;
  float XOffset;
  float YOffset;
  float focalplaneX;
  float focalplaneY;
  float Temp;
  float Press;
  float Humid;
  float TLR;
  float Tai;
};
