struct tcs_kernel_TimeKeeper {
  string<32> private_revCode; //private
  double private_sndStamp; //private
  double private_rcvStamp; //private
  long private_seqNum; //private
  long private_origin; //private
  float Tai;
  float Tt;
  float Cst;
  float Sst;
  float Dcst;
  float Dsst;
};
