struct system_Command_history {


struct system_Computer_status {
  long Raw[16];
  float Calibrated[32];
};




struct system_Hardware_revision_history {
  string<32> Part;
  string<32> Reason;
  long Version[3];
};




struct system_Software_revision_history {
  string<32> PackageName;
  string<32> Notes;
  long Version[3];
};




