struct seeing_dimm_Application {
  long Raw[15];
  float Calibrated[31];
  string<128> Status_1;
  string<128> Status_2;
  string<128> Status_3;
  string<128> Status_4;
  string<128> Status_5;
  string<128> Status_6;
  string<128> Status_7;
  string<128> Status_8;
  string<128> Status_9;
  string<128> Status_10;
  string<128> Status_11;
  string<128> Status_12;
  string<128> Status_13;
  string<128> Status_14;
  string<128> Status_15;
};




struct seeing_dimm_Electrical {
  long Raw[15];
  float Calibrated[31];
  byte Status[15];
};




struct seeing_dimm_Metrology {
  long Raw[15];
  float Calibrated[15];
  byte Limits[63];
  byte Status[63];
};




struct seeing_dimm_Temps {
  long Raw[15];
  float Calibrated[15];
  byte Health[15];
};




struct seeing_dimm_Application {
  long Raw[16];
  float Calibrated[32];
  float Error[4];
  string<16> Status;
};




struct seeing_dimm_Electrical {
  long Raw[16];
  float Calibrated[31];
  octet Status[15];
};




struct seeing_dimm_Measurement {
  long hrnum;
  string<16> utdate;
  string<16> uttime;
  float exposure;
  long numlines;
  float seeing_corr;
  long flux;
  float scintleft;
  float scintright;
  float strehlleft;
  float strehlright;
};




struct seeing_dimm_Metrology {
  long Raw[16];
  float Calibrated[15];
  octet Limits[63];
  octet Status[63];
};




struct seeing_dimm_TC {
  long Raw[16];
  float Calibrated[16];
};




struct seeing_dimm_Temps {
  long Raw[15];
  float Calibrated[15];
  octet Health[15];
};




struct seeing_dimm_command {
  long cmdID;
  string<16> device;
  string<16> operation;
  string<16> value;
  string<128> modifiers;
};




struct seeing_dimm_response {
  long cmdID;
  string<16> ack;
  string<16> error;
  long timeout;
  short repeat;
  short submits;
  string<64> result;
};




