struct calibration_Application {
  float Demand[4];
  float Position[4];
  float Error[4];
  string<16> Status;
};




struct calibration_Electrical {
  long Raw[16];
  float Calibrated[32];
};




struct calibration_Metrology {
  long Raw[16];
  float Calibrated[16];
};




struct calibration_TC {
  long Raw[16];
  float Calibrated[16];
};




struct calibration_command {
  long cmdID;
  string<16> device;
  string<16> operation;
  string<16> value;
  string<128> modifiers;
};




struct calibration_response {
  long cmdID;
  string<16> ack;
  string<16> error;
  long timeout;
  short repeat;
  short submits;
  string<64> result;
};




