struct network_Application {
  long Data[63];
  string<128> Status_1;
  string<128> Status_2;
  string<128> Status_3;
  string<128> Status_4;
  string<128> Status_5;
  string<128> Status_6;
  string<128> Status_7;
  string<128> Status_8;
  string<128> Status_9;
  string<128> Status_10;
  string<128> Status_11;
  string<128> Status_12;
  string<128> Status_13;
  string<128> Status_14;
  string<128> Status_15;




struct network_Application {
  long Data[63];
  string<128> Status_1;
  string<128> Status_2;
  string<128> Status_3;
  string<128> Status_4;
  string<128> Status_5;
  string<128> Status_6;
  string<128> Status_7;
  string<128> Status_8;
  string<128> Status_9;
  string<128> Status_10;
  string<128> Status_11;
  string<128> Status_12;
  string<128> Status_13;
  string<128> Status_14;
  string<128> Status_15;
};




struct network_command {
  long cmdID;
  string<16> device;
  string<16> operation;
  string<16> value;
  string<128> modifiers;
};




struct network_response {
  long cmdID;
  string<16> ack;
  string<16> error;
  long timeout;
  short repeat;
  short submits;
  string<64> result;
};




