struct mount_Alt {
  long Raw[16];
  float Calibrated[32];
};




struct mount_Application {
  float Demand[4];
  float Position[4];
  float Error[4];
  string<16> Status;
};




struct mount_Az {
  long Raw[16];
  float Calibrated[32];
};




struct mount_Electrical {
  long Raw[16];
  float Calibrated[32];
};




struct mount_Metrology {
  long Raw[16];
  float Calibrated[16];
};




struct mount_Rotator {
  long Raw[16];
  float Calibrated[32];
};




struct mount_TC {
  long Raw[16];
  float Calibrated[16];
};




struct mount_command {
  long cmdID;
  string<16> device;
  string<16> operation;
  string<16> value;
  string<128> modifiers;
};




struct mount_response {
  long cmdID;
  string<16> ack;
  string<16> error;
  long timeout;
  short repeat;
  short submits;
  string<64> result;
};




