struct ocs_activity_planning {
  string<128> type;
  string<128> subsystem;
  string<128> part;
  string<128> supervid;
  string<32> uuid;
};




struct ocs_activity_record {
  string<128> type;
  string<128> subsystem;
  string<128> part;
  string<128> supervid;
  string<32> uuid;
};




struct ocs_command_health {
  string<128> subsystem;
  string<128> device;
};




struct ocs_command_permit {
  string<128> subsystem;
  string<128> device;
  string<32> command;
  long actionmask[8];
};




struct ocs_database_state {
  string<64> name;
  string<64> table;
  long status[32];
  long recin[32];
  long recout[32];
  long capacity[32];
  long lastrep[32];
};




struct ocs_operator_log {
  long opid;
  long stationid;
  string<32> subsystem;
  string<32> device;
  string<128> event;
};




struct ocs_pointing_wcs {
  double ra[200];
  double dec[200];
  double coeff[32];
};




struct ocs_scheduler_econstraints {
  string<32> type;
  string<32> minval;
  string<32> maxval;
};




struct ocs_scheduler_iconstraints {
  string<32> type;
  string<32> minval;
  string<32> maxval;
};




struct ocs_scheduler_parameters {
  string<32> algorithm;
  string<32> p1;
  string<32> p2;
  string<32> p3;
  string<32> p4;
};




struct ocs_scheduler_program {
  long id;
  long priority;
  long status;
  float completion;
};




struct ocs_scheduler_progress {
  long taskid[32];
  long priority[32];
  double completion[32];
  long projection[32];
};




struct ocs_scheduler_targets {
  double ra[10];
  double dec[10];
  double catid[10];
  double airmass[10];
  double rotangle[10];
  long filter[10];
  long numexp[10];
};




struct ocs_staticanalysis {
  string<128> subsystem;
  string<128> part;
  float start;
  float end;
  long result;
  long action;
  string<32> actuuid;
};




struct ocs_system {
  long health[500];
  long power[500];
  long thermal[500];
};




struct ocs_system_accesscontrol {
  string<128> subssystem;
  string<128> device;
  string<500> bystation;
  string<500> byoperator;
  string<500> bypolicy;
};




struct ocs_system_configuration {
  string<128> subssystem;
  string<128> device;
  long stationid;
};




struct ocs_system_networking {
  string<128> subsystem;
  string<32> mac;
  long ip[4];
  long rx[6];
  long tx[6];
};




