#
#  SAL test topic to excercise all permitted data types
#

struct sal_SALTOPIC {
  short			test_i16;		//	microns : -1000,1000 : Test signed short
  long			test_l32;		//	microns : -1000,1000 : Test signed 32 bit int
  longlong		test_i64;		//	microns : -1000,1000 : Test signed 64 bit int
  unsigned short	test_u16;		//	microns : -1000,1000 : Test unsigned short
  unsigned long		test_u32;		//	microns : -1000,1000 : Test unsigned 32 bit int
  unsigned longlong	test_u64;		//	microns : -1000,1000 : Test unsigned 64 bit int
  float			test_r32;		//	microns : -1000.,1000. : Test floating point
  double		test_r64;		//	microns : -1000.,1000. : Test double
  char			test_u8;		//	none : none : Test char
  boolean		test_bool;		//	none : none : Test booean
  short			test_i16_array[16];	//	microns : -1000,1000 : Test signed short array
  long			test_l32_array[16];;	//	microns : -1000,1000 : Test signed 32 bit int array
  longlong		test_i64_array[16];;	//	microns : -1000,1000 : Test signed 64 bit int array
  unsigned short	test_u16_array[16];;	//	microns : -1000,1000 : Test unsigned short array
  unsigned long		test_u32_array[16];;	//	microns : -1000,1000 : Test unsigned 32 bit int array
  unsigned longlong	test_u64_array[16];;	//	microns : -1000,1000 : Test unsigned 64 bit int array
  float			test_r32_array[16];;	//	microns : -1000.,1000. : Test float array
  double		test_r64_array[16];;	//	microns : -1000.,1000. : Test double array
  char			test_u8_array[16];;	//	none : none : Test char array
  boolean		test_bool_array[16];;	//	none : none : Test booean array
  string<32>		test_string;		//	none : none : Test string
  string<16>		test_string_option;	//	none : yes,no,maybe : Test string option
  string<4096>		test_large_string;	//	none : none : Test large string
};

