# -*- python -*-
import os

from lsst.sconsUtils import env, scripts
from lsst.ts.sal.make_salpy_lib import make_salpy_lib

scripts.BasicSConscript.tests(pyList=[])

for name in ("OSPL_URI",):
    val = os.environ.get(name)
    if val is not None:
        env.AppendENVPath(name, val)

if not env.GetOption("clean"):
    if len(scripts.BUILD_TARGETS) == 0 or "tests" in scripts.BUILD_TARGETS:
        make_salpy_lib("Test")
        make_salpy_lib("Script")
