/*
 * Please so not edit this file by hand!
 * This file was automatically generated by: nddsgen
 */

#include <rpc/types.h>
#include <rpc/xdr.h>
#include "panoReceive.h"


bool_t
xdr_panoReceiveStruct(XDR *xdrs, panoReceiveStruct *objp)
{
	if (!xdr_int(xdrs, &objp->message)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->flag)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->params, 4, sizeof(int), xdr_int)) {
		return (FALSE);
	}
	return (TRUE);
}


