#----------------------------------------------------------------------------
#       Macros
#----------------------------------------------------------------------------
CFG = Release

ifeq ($(CFG), Release)
CC            = gcc
CXX           = g++
LD            = $(CXX) $(CCFLAGS) $(CPPFLAGS)
AR            = ar
PICFLAGS      = -fPIC
CPPFLAGS      = $(PICFLAGS) $(GENFLAGS) -m32 -D_REENTRANT -Wall -I"../../../../include" -I"../../../../include/sys" -I"../../../../include/dcps/C++/SACPP" -I"$(BOOST_ROOT)/." -I"../../../../include/dcps/C++/isocpp" -I"." -I"../../../../examples/include" -I"../../../../examples"
OBJEXT        = .o
OUTPUT_OPTION = -o "$@"
COMPILE.c     = $(CC) $(CFLAGS) $(CPPFLAGS) -c
COMPILE.cc    = $(CXX) $(CCFLAGS) $(CPPFLAGS) -c
LDFLAGS       = -L"." -L"../../../../lib" -Wl,-rpath,\$$ORIGIN -Wl,-rpath,\$$ORIGIN/../../../../lib
CCC           = $(CXX)
MAKEFILE      = Makefile.ISO_Cxx_SAL_Typesupport
DEPENDENCIES  = .depend.$(MAKEFILE)
LTARGETDIR    = ./
CAT           = cat
MV            = mv -f
RM            = rm -rf
CP            = cp -p
NUL           = /dev/null
MKDIR         = mkdir -p
TESTDIRSTART  = test -d
TESTDIREND    = ||
TOUCH         = touch
EXEEXT        = 
LIBPREFIX     = lib
LIBSUFFIX     = 
GENFLAGS      = -O
LDLIBS        = -l"dcpsisocpp$(LIBSUFFIX)" -l"dcpssacpp" -l"dcpsgapi" -l"ddsuser" -l"ddskernel" -l"ddsserialization" -l"ddsconfparser" -l"ddsconf" -l"ddsdatabase" -l"ddsutil" -l"ddsos" -ldl $(subst lib,-l,$(sort $(basename $(notdir $(wildcard /usr/lib/librt.so /lib/librt.so))))) -lpthread
OBJS          = .obj/SALDataDcps$(OBJEXT) .obj/SALData$(OBJEXT) .obj/SALDataDcps_impl$(OBJEXT) .obj/SALDataSplDcps$(OBJEXT)
AREXT         = .a
LIB           = $(LTARGETDIR)$(LIBPREFIX)ISO_Cxx_SAL_Typesupport$(LIBSUFFIX)$(AREXT)
SOEXT         = .so
SHTARGETDIR   = ./
SHLIB         = $(SHTARGETDIR)$(LIBPREFIX)ISO_Cxx_SAL_Typesupport$(LIBSUFFIX)$(SOEXT)
SHFLAGS       = -shared
SRC           = ./SALDataDcps.cpp ./SALData.cpp ./SALDataDcps_impl.cpp ./SALDataSplDcps.cpp
LINK.cc       = $(LD) $(LDFLAGS)
DYNAMICFLAGS  = -DOSPL_BUILDEXAMPLE_LIB
EXPORTFLAGS   = $(DYNAMICFLAGS)
endif
ifeq ($(CFG), Debug)
CC            = gcc
CXX           = g++
LD            = $(CXX) $(CCFLAGS) $(CPPFLAGS)
AR            = ar
PICFLAGS      = -fPIC
CPPFLAGS      = $(PICFLAGS) $(GENFLAGS) -m32 -D_REENTRANT -Wall -I"../../../../include" -I"../../../../include/sys" -I"../../../../include/dcps/C++/SACPP" -I"$(BOOST_ROOT)/." -I"../../../../include/dcps/C++/isocpp" -I"." -I"../../../../examples/include" -I"../../../../examples"
OBJEXT        = .o
OUTPUT_OPTION = -o "$@"
COMPILE.c     = $(CC) $(CFLAGS) $(CPPFLAGS) -c
COMPILE.cc    = $(CXX) $(CCFLAGS) $(CPPFLAGS) -c
LDFLAGS       = -L"." -L"../../../../lib" -Wl,-rpath,\$$ORIGIN -Wl,-rpath,\$$ORIGIN/../../../../lib
CCC           = $(CXX)
MAKEFILE      = Makefile.ISO_Cxx_SAL_Typesupport
DEPENDENCIES  = .depend.$(MAKEFILE)
LTARGETDIR    = ./
CAT           = cat
MV            = mv -f
RM            = rm -rf
CP            = cp -p
NUL           = /dev/null
MKDIR         = mkdir -p
TESTDIRSTART  = test -d
TESTDIREND    = ||
TOUCH         = touch
EXEEXT        = 
LIBPREFIX     = lib
LIBSUFFIX     = 
GENFLAGS      = -g
LDLIBS        = -l"dcpsisocpp$(LIBSUFFIX)" -l"dcpssacpp" -l"dcpsgapi" -l"ddsuser" -l"ddskernel" -l"ddsserialization" -l"ddsconfparser" -l"ddsconf" -l"ddsdatabase" -l"ddsutil" -l"ddsos" -ldl $(subst lib,-l,$(sort $(basename $(notdir $(wildcard /usr/lib/librt.so /lib/librt.so))))) -lpthread
OBJS          = .obj/SALDataDcps$(OBJEXT) .obj/SALData$(OBJEXT) .obj/SALDataDcps_impl$(OBJEXT) .obj/SALDataSplDcps$(OBJEXT)
AREXT         = .a
LIB           = $(LTARGETDIR)$(LIBPREFIX)ISO_Cxx_SAL_Typesupport$(LIBSUFFIX)$(AREXT)
SOEXT         = .so
SHTARGETDIR   = ./
SHLIB         = $(SHTARGETDIR)$(LIBPREFIX)ISO_Cxx_SAL_Typesupport$(LIBSUFFIX)$(SOEXT)
SHFLAGS       = -shared
SRC           = ./SALDataDcps.cpp ./SALData.cpp ./SALDataDcps_impl.cpp ./SALDataSplDcps.cpp
LINK.cc       = $(LD) $(LDFLAGS)
DYNAMICFLAGS  = -DOSPL_BUILDEXAMPLE_LIB
EXPORTFLAGS   = $(DYNAMICFLAGS)
endif

#----------------------------------------------------------------------------
#       Local targets
#----------------------------------------------------------------------------

all: $(SHLIB)

$(SHLIB): $(OBJS)
	@$(TESTDIRSTART) "$(SHTARGETDIR)" $(TESTDIREND) $(MKDIR) "$(SHTARGETDIR)"
	$(LINK.cc) $(SHFLAGS) $(OBJS) $(LDLIBS) $(OUTPUT_OPTION)

$(LIB): $(OBJS)
	@$(TESTDIRSTART) "$(LTARGETDIR)" $(TESTDIREND) $(MKDIR) "$(LTARGETDIR)"
	$(AR) $(ARFLAGS) $(LIB) $(OBJS) 

SPACE           = $(should_be_unset) $(should_be_unset)
GENERATED_DIRTY = ./SALDataSplDcps.h ./SALDataDcps.cpp ./SALData.cpp ./SALDataDcps_impl.cpp ./SALDataSplDcps.cpp ./SALData_DCPS.hpp ./SALDataDcps_impl.h ./SALDataDcps.h ./SALData.h


.NOTPARALLEL:
./SALDataSplDcps.h ./SALDataDcps.cpp ./SALData.cpp ./SALDataDcps_impl.cpp ./SALDataSplDcps.cpp ./SALData_DCPS.hpp ./SALDataDcps_impl.h ./SALDataDcps.h ./SALData.h: ../idl/SALData.idl
	"../../../../bin/idlpp" -I "../../../../etc/idl" -S -l isocpp ../idl/SALData.idl

.PRECIOUS: $(GENERATED_DIRTY)
$(OBJS): $(GENERATED_DIRTY)

generated: $(GENERATED_DIRTY)
	@-:

.obj/SALDataDcps$(OBJEXT): ./SALDataDcps.cpp
	@$(TESTDIRSTART) ".obj/." $(TESTDIREND) $(MKDIR) ".obj/."
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) ./SALDataDcps.cpp

.obj/SALData$(OBJEXT): ./SALData.cpp
	@$(TESTDIRSTART) ".obj/." $(TESTDIREND) $(MKDIR) ".obj/."
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) ./SALData.cpp

.obj/SALDataDcps_impl$(OBJEXT): ./SALDataDcps_impl.cpp
	@$(TESTDIRSTART) ".obj/." $(TESTDIREND) $(MKDIR) ".obj/."
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) ./SALDataDcps_impl.cpp

.obj/SALDataSplDcps$(OBJEXT): ./SALDataSplDcps.cpp
	@$(TESTDIRSTART) ".obj/." $(TESTDIREND) $(MKDIR) ".obj/."
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) ./SALDataSplDcps.cpp

clean:
	-$(RM) $(OBJS)

realclean: clean
	-$(RM) $(SHLIB) $(LIB)
	-$(RM) $(GENERATED_DIRTY)
	-$(RM) .obj/

check-syntax:
	$(COMPILE.cc) $(EXPORTFLAGS) -Wall -Wextra -pedantic -fsyntax-only $(CHK_SOURCES)

#----------------------------------------------------------------------------
#       Dependencies
#----------------------------------------------------------------------------

$(DEPENDENCIES):
	@$(TOUCH) $(DEPENDENCIES)

depend:
	-VDIR=.obj/ $(MPC_ROOT)/depgen.pl  $(CFLAGS) $(CCFLAGS) $(CPPFLAGS) -f $(DEPENDENCIES) $(SRC) 2> $(NUL)

include $(DEPENDENCIES)
