/*
 * Please so not edit this file by hand!
 * This file was automatically generated by: nddsgen
 */

#include <rpc/types.h>
#include <rpc/xdr.h>
#include "hiResImageSelection.h"


bool_t
xdr_hiResImageSelectionStruct(XDR *xdrs, hiResImageSelectionStruct *objp)
{
	if (!xdr_int(xdrs, &objp->targetID)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->selectionType)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->row)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->col)) {
		return (FALSE);
	}
	return (TRUE);
}


