module camera
{
	struct Cluster_Encoder {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  float	Image_mean[3216];	// 0.054 | none | Mean of image pixels (1/amp) | none | Control room | 3216 |  7,509,795  |  30,039,178 
	  float	Image_SD[3216];	// 0.054 | none | StDev of image pixels (1/amp) | none | Control room | 3216 |  7,509,795  |  30,039,178 
	  float	Overscan_mean[3216];	// 0.054 | none | Mean of overscan pixels (1/amp) | none | Control room | 3216 |  7,509,795  |  30,039,178 
	  float	Overscan_SD[3216];	// 0.054 | none | StDev of overscan pixels (1/amp) | none | Control room | 3216 |  7,509,795  |  30,039,178 
	  float	PSF[9648];	// 0.054 | none | Image PSF (3/amp) | none | Control room | 9648 |  22,529,384  |  90,117,535 
	};
	#pragma keylist Cluster_Encoder
};
