module camera
{
	struct Purge {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  float	Flow_meter;	// 58 | lps | Flow meters |  | Utility trunk | ?? | ?? | ??
	};
	#pragma keylist Purge
	struct Purge_ {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  long	Valve_setting;	// 58 | none | Valve settings |  | Camera body | ?? | ?? | ??
	  float	Flow_meter;	// 58 | lps | Flow meters |  | Camera body | ?? | ?? | ??
	  long	Microphone;	// 58 | none | Microphone |  | Camera body | 1 |  720  | ??
	};
	#pragma keylist Purge_
	struct Purge_acceleration {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  float	Accelerometer[6];	// 58 | m/s2 | Accelerometers |  | Camera body | 6 |  4,320  |  17,280 
	};
	#pragma keylist Purge_acceleration
	struct Purge_current {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  float	Heater_current;	// 58 | Amp | Heater settings |  | Camera body | ?? | ?? | ??
	  float	Heaters;	// 58 | Amp | Heaters |  | Camera body | ?? | ?? | ??
	};
	#pragma keylist Purge_current
	struct Purge_flow {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  float	Flow_meter;	// 58 | lps | Flow meters |  | Utility trunk | ?? | ?? | ??
	  float	Flow_meter;	// 58 | lps | Flow meters |  | Camera body | ?? | ?? | ??
	};
	#pragma keylist Purge_flow
	struct Purge_microphone {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  long	Microphone;	// 58 | none | Microphone |  | Camera body | 1 |  720  | ??
	};
	#pragma keylist Purge_microphone
	struct Purge_speed {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  float	Blower_setting;	// 58 | Hz | Blower speed setting |  | Camera body | 1 |  720  |  2,880 
	  float	Blower_speed;	// 58 | Hz | Blower speed |  | Camera body | 1 |  720  |  2,880 
	};
	#pragma keylist Purge_speed
	struct Purge_status {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  long	Valves;	// 58 | none | Valve statuses  |  | Camera body | ?? | ?? | ??
	};
	#pragma keylist Purge_status
	struct Purge_temperature {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  float	Temp;	// 58 | Celsius | Temperature |  | Utility trunk | ?? | ?? | ??
	  float	Temp;	// 58 | Celsius | Temperature |  | Camera body | ?? | ?? | ??
	};
	#pragma keylist Purge_temperature
	struct Purge_x {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  long	Valve_setting;	// 58 | none | Valve settings |  | Camera body | ?? | ?? | ??
	};
	#pragma keylist Purge_x
};
