module camera
{
	struct SDS_ {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  none	Timing_parameter[10];	// 18 | none | Timing parameters[ | Science and corner rafts | 630 |  1,471,135  |  5,884,541  | 
	  unsigned short	REB_ID;	// none | | Raft Electronics Board ID
	};
	#pragma keylist SDS_
	struct SDS_TCM {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  none	Timing_parameter[10];	// 18 | none | Timing parameters[ | Science and corner rafts | 630 |  1,471,135  |  5,884,541  | 
	  unsigned short	REB_ID;	// none | | Raft Electronics Board ID
	};
	#pragma keylist SDS_TCM
	struct camera_SDS_amplifiers {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  unsigned short	raftID;
	  unsigned long	flags[132];
	  unsigned long	status[132];
	  float	voltage1[132];
	  float	voltage2[132];
	  float	voltage3[132];
	  float	voltage4[132];
	};
	struct SDS_status {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  none	flag[20];	// 18 | none | Error flags[ | Science and corner rafts | 1260 |  2,942,270  |  11,769,081  | 
	  unsigned short	REB_ID;	// none | | Raft Electronics Board ID
	};
	#pragma keylist SDS_status
};
