//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: SALData.cpp
//  Source: ../../idl/SALData.idl
//  Generated: Mon May 27 11:36:38 2013
//  OpenSplice V6.3.0
//  
//******************************************************************

#include "SALData.h"




