//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: SALData.h
//  Source: ../../idl/SALData.idl
//  Generated: Mon May 27 11:36:38 2013
//  OpenSplice V6.3.0
//  
//******************************************************************
#ifndef _SALDATA_H_
#define _SALDATA_H_

#include "sacpp_mapping.h"
#include "sacpp_DDS_DCPS.h"

namespace SALData
{
   struct SALTopic;
   struct SALCommand;
   struct SALResponse;
   struct SALEvent;

   struct SALTopic
   {
      DDS::String_mgr private_revCode;
      DDS::Double private_sndStamp;
      DDS::Double private_rcvStamp;
      DDS::Long private_origin;
   };

   typedef DDS_DCPSStruct_var < SALTopic> SALTopic_var;
   typedef DDS_DCPSStruct_out < SALTopic> SALTopic_out;

   struct SALCommand
   {
      DDS::String_mgr private_revCode;
      DDS::Double private_sndStamp;
      DDS::Double private_rcvStamp;
      DDS::Long private_origin;
      DDS::Long private_seqNum;
      DDS::String_mgr device;
      DDS::String_mgr property;
      DDS::String_mgr action;
      DDS::String_mgr value;
      DDS::String_mgr modifiers;
   };

   typedef DDS_DCPSStruct_var < SALCommand> SALCommand_var;
   typedef DDS_DCPSStruct_out < SALCommand> SALCommand_out;

   struct SALResponse
   {
      DDS::String_mgr private_revCode;
      DDS::Double private_sndStamp;
      DDS::Double private_rcvStamp;
      DDS::Long private_origin;
      DDS::Long private_seqNum;
      DDS::Long ack;
      DDS::Long error;
      DDS::String_mgr result;
   };

   typedef DDS_DCPSStruct_var < SALResponse> SALResponse_var;
   typedef DDS_DCPSStruct_out < SALResponse> SALResponse_out;

   struct SALEvent
   {
      DDS::String_mgr private_revCode;
      DDS::Double private_sndStamp;
      DDS::Double private_rcvStamp;
      DDS::Long private_origin;
      DDS::String_mgr message;
   };

   typedef DDS_DCPSStruct_var < SALEvent> SALEvent_var;
   typedef DDS_DCPSStruct_out < SALEvent> SALEvent_out;
}




#endif 
