module camera
{
	struct GDS_TCM {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  none	Timing_parameter[10];	// 0.054 | none | Timing parameters[ | Science and corner rafts | 40 |  93,405  |  373,622  | 
	  unsigned short	REB_ID;	// none | | Raft Electronics Board ID
	};
	#pragma keylist GDS_TCM
	struct GDS_status {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  none	flag[20];	// 0.054 | none | Error flags[ | Science and corner rafts | 80 |  186,811  |  747,243  | 
	  unsigned short	REB_ID;	// none | | Raft Electronics Board ID
	};
	#pragma keylist GDS_status
};
