#include "svcSAL_system_Command_history.h"
#include "svcSAL_system_Computer_status.h"
#include "svcSAL_system_Hardware_revision_history.h"
#include "svcSAL_system_Software_revision_history.h"
#define SAL_IID_system_Command_history 0x9170ea
#define SAL_IID_system_Computer_status 0x2e4113
#define SAL_IID_system_Hardware_revision_history 0xc9f478
#define SAL_IID_system_Software_revision_history 0x40a8b6
