/*
 * Please so not edit this file by hand!
 * This file was automatically generated by: nddsgen
 */

#include <rpc/types.h>
#include <rpc/xdr.h>
#include "hiResImageRequest.h"


bool_t
xdr_hiResImageRequestStruct(XDR *xdrs, hiResImageRequestStruct *objp)
{
	if (!xdr_int(xdrs, &objp->targetID)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->row)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->col)) {
		return (FALSE);
	}
	if (!xdr_float(xdrs, &objp->relativeZoomFactor)) {
		return (FALSE);
	}
	if (!xdr_float(xdrs, &objp->focus)) {
		return (FALSE);
	}
	return (TRUE);
}


