/*
 * Please so not edit this file by hand!
 * This file was automatically generated by: nddsgen
 */

#include <rpc/types.h>
#include <rpc/xdr.h>
#include "ImageSequence.h"


bool_t
xdr_ImageSequenceStruct(XDR *xdrs, ImageSequenceStruct *objp)
{
	if (!xdr_int(xdrs, &objp->headerId)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->x1)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->y1)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->x2)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->y2)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->sequenceType)) {
		return (FALSE);
	}
	return (TRUE);
}


