/*
 * Please so not edit this file by hand!
 * This file was automatically generated by: nddsgen
 */

#include <rpc/types.h>
#include <rpc/xdr.h>
#include "gpsRawState.h"


bool_t
xdr_gpsRawStateStruct(XDR *xdrs, gpsRawStateStruct *objp)
{
	if (!xdr_double(xdrs, &objp->receiveTime)) {
		return (FALSE);
	}
	if (!xdr_double(xdrs, &objp->clockOffset)) {
		return (FALSE);
	}
	if (!xdr_u_int(xdrs, &objp->numSVSVisible)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->visibleSvsPRN, 10, sizeof(u_int), xdr_u_int)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->svFlags1, 10, sizeof(u_int), xdr_u_int)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->svFlags2, 10, sizeof(u_int), xdr_u_int)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->svsElevation, 10, sizeof(int), xdr_int)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->svsAzimuth, 10, sizeof(int), xdr_int)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->svsL1SNR, 10, sizeof(int), xdr_int)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->svsL2SNR, 10, sizeof(int), xdr_int)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->L1PseudoRange, 10, sizeof(double), xdr_double)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->L1ContPhase, 10, sizeof(double), xdr_double)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->L1Doppler, 10, sizeof(float), xdr_float)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->L2ContPhase, 10, sizeof(double), xdr_double)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->L2L1PseudoRange, 10, sizeof(float), xdr_float)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->issueOfDataEphem, 10, sizeof(int), xdr_int)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->L1Slip, 10, sizeof(int), xdr_int)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->L2Slip, 10, sizeof(int), xdr_int)) {
		return (FALSE);
	}
	if (!xdr_double(xdrs, &objp->wgs84Latitude)) {
		return (FALSE);
	}
	if (!xdr_double(xdrs, &objp->wgs84Longitude)) {
		return (FALSE);
	}
	if (!xdr_double(xdrs, &objp->wgs84Altitude)) {
		return (FALSE);
	}
	if (!xdr_double(xdrs, &objp->positionDOP)) {
		return (FALSE);
	}
	if (!xdr_double(xdrs, &objp->latitudeRate)) {
		return (FALSE);
	}
	if (!xdr_double(xdrs, &objp->longitudeRate)) {
		return (FALSE);
	}
	if (!xdr_double(xdrs, &objp->altitudeRate)) {
		return (FALSE);
	}
	if (!xdr_u_long(xdrs, &objp->msecOfGPSWeek)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->positionflags)) {
		return (FALSE);
	}
	if (!xdr_u_int(xdrs, &objp->numSVSTracked)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->svsChannelNumber, 10, sizeof(u_int), xdr_u_int)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->trackedSVS_PRN, 10, sizeof(u_int), xdr_u_int)) {
		return (FALSE);
	}
	if (!xdr_u_int(xdrs, &objp->msecs)) {
		return (FALSE);
	}
	if (!xdr_u_int(xdrs, &objp->week)) {
		return (FALSE);
	}
	return (TRUE);
}


