/*
 * Please so not edit this file by hand!
 * This file was automatically generated by: nddsgen
 */

#include <rpc/types.h>
#include <rpc/xdr.h>
#include "imuDerivedState.h"


bool_t
xdr_imuDerivedStateStruct(XDR *xdrs, imuDerivedStateStruct *objp)
{
	if (!xdr_vector(xdrs, (char *)objp->rotDot, 3, sizeof(float), xdr_float)) {
		return (FALSE);
	}
	if (!xdr_u_int(xdrs, &objp->msecs)) {
		return (FALSE);
	}
	if (!xdr_u_int(xdrs, &objp->week)) {
		return (FALSE);
	}
	return (TRUE);
}


