/*
 * Please so not edit this file by hand!
 * This file was automatically generated by: nddsgen
 */

#include <rpc/types.h>
#include <rpc/xdr.h>
#include "kvhDerivedState.h"


bool_t
xdr_kvhDerivedStateStruct(XDR *xdrs, kvhDerivedStateStruct *objp)
{
	if (!xdr_int(xdrs, &objp->pitch)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->roll)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->magneticAzimuth)) {
		return (FALSE);
	}
	if (!xdr_u_int(xdrs, &objp->msecs)) {
		return (FALSE);
	}
	if (!xdr_u_int(xdrs, &objp->week)) {
		return (FALSE);
	}
	return (TRUE);
}


