/*
 * Please so not edit this file by hand!
 * This file was automatically generated by: nddsgen
 */

#include <rpc/types.h>
#include <rpc/xdr.h>
#include "lasRawScanData.h"


bool_t
xdr_lasRawScanDataStruct(XDR *xdrs, lasRawScanDataStruct *objp)
{
	if (!xdr_vector(xdrs, (char *)objp->scanMap, 361, sizeof(u_int), xdr_u_int)) {
		return (FALSE);
	}
	if (!xdr_u_int(xdrs, &objp->resolution)) {
		return (FALSE);
	}
	if (!xdr_u_int(xdrs, &objp->sampleRate)) {
		return (FALSE);
	}
	if (!xdr_u_int(xdrs, &objp->msecs)) {
		return (FALSE);
	}
	if (!xdr_u_int(xdrs, &objp->week)) {
		return (FALSE);
	}
	return (TRUE);
}


