/*
 * Please so not edit this file by hand!
 * This file was automatically generated by: nddsgen
 */

#include <rpc/types.h>
#include <rpc/xdr.h>
#include "morInternalState.h"


bool_t
xdr_morInternalStateStruct(XDR *xdrs, morInternalStateStruct *objp)
{
	if (!xdr_vector(xdrs, (char *)objp->morphinSteer, 2, sizeof(float), xdr_float)) {
		return (FALSE);
	}
	if (!xdr_u_int(xdrs, &objp->msecs)) {
		return (FALSE);
	}
	if (!xdr_u_int(xdrs, &objp->week)) {
		return (FALSE);
	}
	return (TRUE);
}


