struct calibration_Application {
  string<32> private_revCode;  //private
  double     private_sndStamp; //private
  double     private_rcvStamp; //private
  long       private_seqNum;   //private
  long       private_origin;   //private
  float	Demand[4];
  float	Position[4];
  float	Error[4];
  string<16>	Status;
};
