struct Filter_current {
  string<32> private_revCode;  //private
  double     private_sndStamp; //private
  double     private_rcvStamp; //private
  long       private_seqNum;   //private
  long       private_origin;   //private
  float	Carousel_current;	// 2.31E-04 | Amp | Carousel: motor current | none | Camera body | 1 |  10  |  40 
  float	Auto_current;	// 2.31E-04 | Amp | Auto: Motor current | none | Camera body | 1 |  10  |  40 
};
#pragma keylist Filter_current
