struct Filter_speed {
  string<32> private_revCode;  //private
  double     private_sndStamp; //private
  double     private_rcvStamp; //private
  long       private_seqNum;   //private
  long       private_origin;   //private
  float	Carousel_speed;	// 2.31E-04 | m/s | Carousel: Speed | none | Camera body | 1 |  10  |  40 
  float	Truck_speed;	// 2.31E-04 | m/s | Auto: Truck speed | none | Camera body | 1 |  10  |  40 
};
#pragma keylist Filter_speed
