struct camera_BEE_clocks {
  string<32> private_revCode;  //private
  double     private_sndStamp; //private
  double     private_rcvStamp; //private
  long       private_seqNum;   //private
  long       private_origin;   //private
  long	serial_1A[201];
  long	serial_2A[201];
  long	serial_3A[201];
  long	serial_1B[201];
  long	serial_2B[201];
  long	serial_3B[201];
  long	parallel_1A[201];
  long	parallel_1B[201];
  long	parallel_2A[201];
  long	parallel_2B[201];
};
#pragma keylist camera_BEE_clocks
