struct camera_FCS {
  string<32> private_revCode;  //private
  double     private_sndStamp; //private
  double     private_rcvStamp; //private
  long       private_seqNum;   //private
  long       private_origin;   //private
  float	motion_profile[2400];
  string<32>	algorithm;
  unsigned long	flags;
};
