struct WAS_current {
  string<32> private_revCode;  //private
  double     private_sndStamp; //private
  double     private_rcvStamp; //private
  long       private_seqNum;   //private
  long       private_origin;   //private
  float	Board_current[4];	// 0.054 | Volt | Electronics board currents (4/board) | none | Corner rafts | 32 |  74,724  |  298,897 
  unsigned short	REB_ID;	// none | | Raft Electronics Board ID
};
#pragma keylist WAS_current
