struct camera_TC_zone4 {
  string<32> private_revCode;  //private
  double     private_sndStamp; //private
  double     private_rcvStamp; //private
  long       private_seqNum;   //private
  long       private_origin;   //private
  float	flow_rate[10];
  float	temperature[10];
  float	setpoint[10];
  long	status[10];
};
#pragma keylist camera_TC_zone4
