struct GAS_ID {
  string<32> private_revCode;  //private
  double     private_sndStamp; //private
  double     private_rcvStamp; //private
  long       private_seqNum;   //private
  long       private_origin;   //private
  short	CCD_ID;	// 2.31E-05 | none | CCD ID ( ITL only) | none | Corner rafts | 4 |  4  |  8 
  short	Board_ID;	// 2.31E-05 | none | Board ID | none | Corner rafts | 4 |  4  |  8 
  unsigned short	REB_ID;	// none | | Raft Electronics Board ID
};
#pragma keylist GAS_ID
