struct SDS_TCM {
  string<32> private_revCode;  //private
  double     private_sndStamp; //private
  double     private_rcvStamp; //private
  long       private_seqNum;   //private
  long       private_origin;   //private
  none	Timing_parameter[10];	// 0.054 | none | Timing parameters[ | Science and corner rafts | 630 |  1,471,135  |  5,884,541  | 
  unsigned short	REB_ID;	// none | | Raft Electronics Board ID
};
#pragma keylist SDS_TCM
