struct PCMS_Status {
  string<32> private_revCode;  //private
  double     private_sndStamp; //private
  double     private_rcvStamp; //private
  long       private_seqNum;   //private
  long       private_origin;   //private
  short	FPGA_Status;	// 0.054 | none | FPGA Status | none | Utility trunk | 75 |  175,135  |  350,270 
  short	Low_Status;	// 0.054 | none | Low Status | none | Utility trunk | 75 |  175,135  |  350,270 
  short	Clock_Status;	// 0.054 | none | Clock Status | none | Utility trunk | 75 |  175,135  |  350,270 
  short	OD_Status;	// 0.054 | none | OD Status | none | Utility trunk | 75 |  175,135  |  350,270 
  short	Bias_Status;	// 0.054 | none | Bias Status | none | Utility trunk | 75 |  175,135  |  350,270 
  unsigned short	REB_ID;	// none | | Raft Electronics Board ID
};
#pragma keylist PCMS_Status
