struct Purge_x {
  string<32> private_revCode;  //private
  double     private_sndStamp; //private
  double     private_rcvStamp; //private
  long       private_seqNum;   //private
  long       private_origin;   //private
  long	Valve_setting;	// 0.017 | none | Valve settings |  | Camera body | ?? | ?? | ??
};
#pragma keylist Purge_x
