struct ocs_scheduler_progress {
  string<32> private_revCode;  //private
  double     private_sndStamp; //private
  double     private_rcvStamp; //private
  long       private_seqNum;   //private
  long       private_origin;   //private
  long	taskid[32];
  long	priority[32];
  double	completion[32];
  long	projection[32];
};
