struct ocs_system {
  string<32> private_revCode;  //private
  double     private_sndStamp; //private
  double     private_rcvStamp; //private
  long       private_seqNum;   //private
  long       private_origin;   //private
  long	health[500];
  long	power[500];
  long	thermal[500];
};
