struct system_Hardware_revision_history {
  string<32> private_revCode;  //private
  double     private_sndStamp; //private
  double     private_rcvStamp; //private
  long       private_seqNum;   //private
  long       private_origin;   //private
  string<32>	Part;
  string<32>	Reason;
  long	Version[3];
};
