/*
 * Please so not edit this file by hand!
 * This file was automatically generated by: nddsgen
 */

#include <rpc/types.h>
#include <rpc/xdr.h>
#include "specReply.h"


bool_t
xdr_specReplyStruct(XDR *xdrs, specReplyStruct *objp)
{
	if (!xdr_int(xdrs, &objp->sensorStatus)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->extendedSensorStatus)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->listFileName, 128, sizeof(char), xdr_char)) {
		return (FALSE);
	}
	if (!xdr_float(xdrs, &objp->deploymentCost)) {
		return (FALSE);
	}
	return (TRUE);
}


