/*
 * Please so not edit this file by hand!
 * This file was automatically generated by: nddsgen
 */

#include <rpc/types.h>
#include <rpc/xdr.h>
#include "navPlanStatus.h"


bool_t
xdr_navPlanStatusStruct(XDR *xdrs, navPlanStatusStruct *objp)
{
	if (!xdr_int(xdrs, &objp->taskMode)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->status)) {
		return (FALSE);
	}
	if (!xdr_float(xdrs, &objp->timeCost)) {
		return (FALSE);
	}
	if (!xdr_float(xdrs, &objp->areaCovered)) {
		return (FALSE);
	}
	if (!xdr_float(xdrs, &objp->energyGen)) {
		return (FALSE);
	}
	return (TRUE);
}


