set ALIASES "home move position offset pivot lut limits acceleration velocity stop"
set CMDS(hexapod,acceleration,freq) ""
set CMDS(hexapod,move,param) "{double	angle}"
set CMDS(hexapod,acceleration,param) "{double	xmin} {double	xmax} {double	ymin} {double	ymax} {double	zmin} {double	zmax} {double	umin} {double	umax} {double	vmin} {double	vmax} {double	wmin} {double	wmax}"
set CMDS(hexapod,move) "target position"
set CMDS(hexapod,stop,freq) ""
set CMDS(hexapod,home) "target position home"
set CMDS(hexapod,move,freq) " 20"
set CMDS(hexapod,acceleration) "drive acceleration"
set CMDS(hexapod,lut,param) "{double	xlut\[90\]} {double	ylut\[90\]} {double	zlut\[90\]} {double	ulut\[90\]} {double	vlut\[90\]} {double	wlut\[90\]}"
set CMDS(hexapod,position,param) "{double	x} {double	y} {double	z} {double	u} {double	v} {double	w} {bool	sync}"
set CMDS(hexapod,home,freq) ""
set CMDS(hexapod,velocity,param) "{double	xmin} {double	xmax} {double	ymin} {double	ymax} {double	zmin} {double	zmax} {double	umin} {double	umax} {double	vmin} {double	vmax} {double	wmin} {double	wmax}"
set CMDS(hexapod,limits,freq) ""
set CMDS(hexapod,pivot,freq) ""
set CMDS(hexapod,offset,param) "{double	x} {double	y} {double	z} {double	u} {double	v} {double	w} {bool	sync}"
set CMDS(hexapod,lut) "target lut"
set CMDS(hexapod,position) "actuators position absolute"
set CMDS(hexapod,stop) "stop"
set CMDS(hexapod,velocity) "drive velocity"
set CMDS(hexapod,limits,param) "{long	xmin} {long 	xmax} {long	ymin} {long 	ymax} {long	zmin} {long 	zmax} {long	umin} {long 	umax} {long	vmin} {long 	vmax} {long	wwmin} {long 	wmax}"
set CMDS(hexapod,lut,freq) ""
set CMDS(hexapod,pivot,param) "{double	x} {double	y} {double	z}"
set CMDS(hexapod,position,freq) ""
set CMDS(hexapod,offset) "actuators position offset"
set CMDS(hexapod,velocity,freq) ""
set CMDS(hexapod,offset,freq) ""
set CMDS(hexapod,limits) "actuators limits"
set CMDS(hexapod,pivot) "actuators pivot"
