struct camera_Cryo_current {
  string<32> private_revCode;  //private
  double     private_sndStamp; //private
  double     private_rcvStamp; //private
  long       private_seqNum;   //private
  long       private_origin;   //private
  float	Heater_current[6];	// 0.010 | Amp | Cryoplate heater currents | none | Cryostat | 6 | 2,592  | 10,368 
};
#pragma keylist camera_Cryo_current 
