struct camera_Cryo_temperature {
  string<32> private_revCode;  //private
  double     private_sndStamp; //private
  double     private_rcvStamp; //private
  long       private_seqNum;   //private
  long       private_origin;   //private
  float	Cold_temperature[3];	// 0.010 | Kelvin | Straps, cryoplate, coldplate (3/raft) | none | Cryostat | 75 | 32,400  | 129,600 
  float	Cryo_temperature[12];	// 0.010 | Kelvin | L3 flange, etc. | none | Cryostat | 12 | 5,184  | 20,736 
  float	Intake_temp[2];	// 0.010 | Celsius | Compressor intake temperature | none | Utility room | 2 | 864  | 3,456 
  float	Pre_expansion_temp[2];	// 0.010 | Celsius | Pre-expansion C4 temperature | none | Cryostat or utility trunk | 2 | 864  | 3,456 
  float	Post_expansion_temp[2];	// 0.010 | Celsius | Post-evaporator temperature | none | Cryostat or utility trunk | 2 | 864  | 3,456 
  float	Return_temp[2];	// 0.010 | Celsius | Return line temperature | none | Cryostat or utility trunk | 2 | 864  | 3,456 
};
#pragma keylist camera_Cryo_temperature 
