module environment
{
	struct Dust_monitor {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  long	Raw[16];
	  float	Calibrated[32];
	#pragma keylist Dust_monitor
	};
	struct Electrical {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  long	Raw[16];
	  float	Calibrated[32];
	#pragma keylist Electrical
	};
	struct Lightning_detector {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  long	Raw[16];
	  float	Calibrated[32];
	#pragma keylist Lightning_detector
	};
	struct Seismometer {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  long	Raw[16];
	  float	Calibrated[32];
	#pragma keylist Seismometer
	};
	struct TC {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  long	Raw[64];
	  float	Calibrated[64];
	#pragma keylist TC
	};
	struct Video_cameras {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  long	Raw[16];
	  float	Calibrated[32];
	#pragma keylist Video_cameras
	};
	struct Weather {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  long	Raw[128];
	  float	Calibrated[256];
	#pragma keylist Weather
	};
};
