module tcs
{
	struct kernel_DawdleFilter {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  long	Bypass;
	  float	T;
	#pragma keylist kernel_DawdleFilter
	};
	struct kernel_FK5Target {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  float	ra;
	  float	dec;
	  float	equinox;
	  float	epoc;
	  float	pmRA;
	  float	pmDec;
	  float	parallax;
	  float	rv;
	#pragma keylist kernel_FK5Target
	};
	struct kernel_OpticsVt {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  float	tip;
	  float	tilt;
	#pragma keylist kernel_OpticsVt
	};
	struct kernel_PointingControl {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  string<32>	RollFilter;
	  string<32>	PitchFilter;
	  float	AGuide;
	  float	BGuide;
	  float	ALocal;
	  float	BLocal;
	#pragma keylist kernel_PointingControl
	};
	struct kernel_PointingLog {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  float	Ra;
	  float	Dec;
	  float	Wavel;
	  float	Roll;
	  float	Pitch;
	  float	Casspa;
	  float	Xr;
	  float	Yr;
	  float	Fl;
	  float	Temp;
	  float	Press;
	  float	Humid;
	  float	Tlr;
	  float	Rcorr;
	  float	Aux[3];
	  long	Marked;
	#pragma keylist kernel_PointingLog
	};
	struct kernel_PointingModel {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  long	Model[30];
	  float	Coeffv[100];
	  long	Nterml;
	  long	Ntermx;
	  long	Nterms;
	  string<32>	Coeff1;
	  string<32>	Coeff2;
	  string<32>	Coeff3;
	  string<32>	Coeff4;
	  string<32>	Coeff5;
	  string<32>	Coeff6;
	  string<32>	Coeff7;
	  string<32>	Coeff8;
	  string<32>	Coeff9;
	  string<32>	Cofor1;
	  string<32>	Cofor2;
	  string<32>	Cofor3;
	  string<32>	Cofor4;
	  string<32>	Cofor5;
	  string<32>	Cofor6;
	  string<32>	Cofor7;
	  string<32>	Cofor8;
	  string<32>	Cofor9;
	#pragma keylist kernel_PointingModel
	};
	struct kernel_Site {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  float	tai;
	  float	delat;
	  float	delut;
	  float	ttmtat;
	  float	elongm;
	  float	latm;
	  float	hm;
	  float	xpm;
	  float	ypm;
	  float	Ttmtai;
	  float	Elong;
	  float	Lat;
	  float	Uau;
	  float	Vau;
	  float	Ukm;
	  float	Vkm;
	  float	Diurab;
	  float	T0;
	  float	St0;
	  float	Tt0;
	  float	Ttj;
	  float	Amprms[21];
	  float	Aoprms[15];
	  float	Refa;
	  float	Refb;
	  float	Daz;
	#pragma keylist kernel_Site
	};
	struct kernel_Target {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  string<128>	site;
	  float	t0;
	  float	az;
	  float	el;
	  float	azdot;
	  float	eldot;
	  float	Wavel;
	  float	XOffset;
	  float	YOffset;
	  string<128>	OffSys;
	  float	focalplaneX;
	  float	focalplaneY;
	  float	Temp;
	  float	Press;
	  float	Humid;
	  float	TLR;
	  float	Tai;
	#pragma keylist kernel_Target
	};
	struct kernel_TimeKeeper {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  float	Tai;
	  float	Tt;
	  float	Cst;
	  float	Sst;
	  float	Dcst;
	  float	Dsst;
	#pragma keylist kernel_TimeKeeper
	};
	struct kernel_TrackRefSys {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  float	tdbj;
	  float	amprms[21];
	  float	ae2mt[9];
	  float	hm;
	  float	tlat;
	  float	diurab;
	  float	refa;
	  float	refb;
	  float	temp;
	  float	press;
	  float	humid;
	  float	tlr;
	  float	wavel;
	  float	sst;
	  float	cst;
	#pragma keylist kernel_TrackRefSys
	};
	struct kernel_TrackingTarget {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  float	PositionX;
	  float	PositionY;
	  float	T0;
	  float	VelocityX;
	  float	VelocityY;
	#pragma keylist kernel_TrackingTarget
	};
};
