module m2
{
	struct Actuators {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  long	Raw[15];
	  float	Calibrated[31];
	  octet	Status[15];
	#pragma keylist Actuators
	};
	struct Application {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  float	Demand[2];
	  float	Position[2];
	  float	Error[2];
	  string<128>	Status_1;
	  string<128>	Status_2;
	  string<128>	Status_3;
	  string<128>	Status_4;
	  string<128>	Status_5;
	  string<128>	Status_6;
	  string<128>	Status_7;
	  string<128>	Status_8;
	  string<128>	Status_9;
	  string<128>	Status_10;
	  string<128>	Status_11;
	  string<128>	Status_12;
	  string<128>	Status_13;
	  string<128>	Status_14;
	  string<128>	Status_15;
	#pragma keylist Application
	};
	struct Electrical {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  long	voltage[16];
	  long	error[16];
	  short	status[16];
	#pragma keylist Electrical
	};
	struct Hexapod {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  long	Raw[31];
	  float	Calibrated[31];
	  octet	Status[31];
	#pragma keylist Hexapod
	};
	struct LimitSensors {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  short	liftoff[64];
	  short	limit[64];
	#pragma keylist LimitSensors
	};
	struct Metrology {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  long	distance[16];
	  long	error[16];
	  short	status[16];
	#pragma keylist Metrology
	};
	struct Surface {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  long	Raw[200];
	  float	Calibrated[200];
	  octet	Status[50];
	#pragma keylist Surface
	};
	struct TC {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  float	setpoint[16];
	  float	temperature[16];
	  float	error[16];
	  short	status[16];
	#pragma keylist TC
	};
	struct Temps {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  long	Raw_[15];
	  float	Calibrated[15];
	  octet	Health[15];
	#pragma keylist Temps
	};
	struct actuators {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  long	targetpos[72];
	  long	stepcnt[72];
	  float	force[72];
	#pragma keylist actuators
	};
};
