struct camera_Purge_microphone {
  string<32> private_revCode;  //private
  double     private_sndStamp; //private
  double     private_rcvStamp; //private
  long       private_seqNum;   //private
  long       private_origin;   //private
  long	Microphone;	// 0.017 | none | Microphone |  | Camera body | 1 | 720  | ??
};
#pragma keylist camera_Purge_microphone 
