struct m2_Metrology {
  string<32> private_revCode; //private
  double private_sndStamp; //private
  double private_rcvStamp; //private
  long private_seqNum; //private
  long private_origin; //private
  long distance[16];
  long error[16];
  short status[16];
};
