/* nddstcl.c

   Kurt Schwehr - August 1996

   This is the main initialization for a Tcl that knows how to 
   talk to NDDS.  This file uses code automatically generated by the
   nddstcl program that parses XDR data structure specification files.

   Used Alex Derbes serialWish as the starting point for this file.

   This code will probably take a lot from Dan Christian's nddswish,
   which can be found in $ROVERHOME/usr/src/tcl/nddsInit.c

   Shared memory code removed.  It was only used to interface with VEVI.

   - Merged into nddswish.c (Dan Christian's code) Aug 20, 1996
   - Converted to a Tcl only version Sept 11, 1996.  Dan Christian
*/

#include <stdio.h>
#include <tcl.h>

extern int GetTclDate (ClientData c, Tcl_Interp *i, int ac, char **av);

int NddsWishInit (Tcl_Interp *interp);


int OurTclInit (Tcl_Interp *interp)
{
    char *rc_file;

					/* these 3 setup calls are mandatory */
    if (Tcl_Init(interp) == TCL_ERROR) {
	printf ("Tcl_Init failed!\n");
        return TCL_ERROR;
    }

    if (NddsWishInit(interp) == TCL_ERROR) { /* NDDS extension */
	printf ("ndds_Init failed!\n");
	return TCL_ERROR;
    }

    Tcl_CreateCommand(interp, "getdatestring", GetTclDate, (ClientData) NULL,
		      (void (*)()) NULL);

    /*
     * Specify a user-specific startup file to invoke if the application
     * is run interactively.  Typically the startup file is "~/.apprc"
     * where "app" is the name of the application.  If this line is deleted
     * then no user-specific startup file will be run under any conditions.
     */

    rc_file = Tcl_SetVar(interp, "tcl_rcFileName", "~/.nddstclrc", TCL_GLOBAL_ONLY);

    if (NULL == rc_file) {
	printf ("Error: init setting rc_file variable\n");
	return TCL_ERROR;
    }

    return (TCL_OK);
}

#ifdef SunOS
#define NASTY_SUNOS_4_1_3_HACK
#endif

#ifdef NASTY_SUNOS_4_1_3_HACK
#include <math.h>       /* ld.so complains about no acos on SunOS 4.1.3 ??? */
#endif

int
main (int argc, char **argv)
{

/* "UGH" -Kurt */
#ifdef NASTY_SUNOS_4_1_3_HACK
    float blah;
    /* Math lib linking problems because of ??? */
    blah = acos (0.3);          /* FIX: Get rid of this when fix sun crap */
    blah = asin (0.3);          /* FIX: Get rid of this when fix sun crap */
    blah = cosh (1.3);
    blah = sinh (1.3);
    blah = hypot (1.3);
    blah = log (1.3);
    blah = log10 (1.3);
    blah = pow(2,4);
    blah = tanh (1.3);
#endif

    Tcl_Main (argc, argv, OurTclInit);	/* never returns */
    return (0);				/* keep compiler happy */
}
