struct camera_Purge_temperature {
  string<32> private_revCode;  //private
  double     private_sndStamp; //private
  double     private_rcvStamp; //private
  long       private_seqNum;   //private
  long       private_origin;   //private
  float	Temp;	// 0.017 | Celsius | Temperature |  | Utility trunk | ?? | ?? | ??
  float	Temp;	// 0.017 | Celsius | Temperature |  | Camera body | ?? | ?? | ??
};
#pragma keylist camera_Purge_temperature 
