struct camera_Cryo {
  float	Pre_expansion_pressure[2];	// 0.010 | Pa | Pre-expansion C4 pressure | none | Cryostat or utility trunk | 2 | 864  | 3,456 
  float	Post_expansion_pressure[2];	// 0.010 | Pa | Post-evaporator pressure | none | Cryostat or utility trunk | 2 | 864  | 3,456 
  float	Compressor_speed[2];		// 0.010 | Hz | Compressor speed | none | Utility room | 2 | 864  | 3,456 
  float	Dischaarge_pressure[2];		// 0.010 | Pa | Compressor discharge  pressure | none | Utility room | 2 | 864  | 3,456 
  float	Discharge_temp[2];		// 0.010 | Celsius | Compressor discharge  temperature | none | Utility room | 2 | 864  | 3,456 
  float	Cold_temperature[3];		// 0.010 | Kelvin | Straps, cryoplate, coldplate (3/raft) | none | Cryostat | 75 | 32,400  | 129,600 
  float	Cryo_temperature[12];		// 0.010 | Kelvin | L3 flange, etc. | none | Cryostat | 12 | 5,184  | 20,736 
  float	Intake_temp[2];			// 0.010 | Celsius | Compressor intake temperature | none | Utility room | 2 | 864  | 3,456 
  float	Pre_expansion_temp[2];		// 0.010 | Celsius | Pre-expansion C4 temperature | none | Cryostat or utility trunk | 2 | 864  | 3,456 
  float	Post_expansion_temp[2];		// 0.010 | Celsius | Post-evaporator temperature | none | Cryostat or utility trunk | 2 | 864  | 3,456 
  float	Return_temp[2];			// 0.010 | Celsius | Return line temperature | none | Cryostat or utility trunk | 2 | 864  | 3,456 
  float	Heater_voltage[6];		// 0.010 | Volt | Cryoplate heater voltages | none | Cryostat | 6 | 2,592  | 10,368 
};
#pragma keylist camera_Cryo
