struct camera_Filter_status {
  string<32> private_revCode;  //private
  double     private_sndStamp; //private
  double     private_rcvStamp; //private
  long       private_seqNum;   //private
  long       private_origin;   //private
  short	Filter_presence[10];	// 2.31E-04 | none | FCS: 10 filter presence sensors | none | Camera body | 10 | 100  | 200 
  short	Brake_status;	// 2.31E-04 | none | Carousel: Brake sensor | none | Camera body | 1 | 10  | 20 
  short	Clamp_status[5];	// 2.31E-04 | none | Auto: Clamp locking sensors | none | Camera body | 5 | 50  | 100 
};
#pragma keylist camera_Filter_status 
