const M1M3NUMACT=120
  long stepcnt[6];		//	none : none : Stepper Motor actual position
  float force[6];		//	none : none : Measured force
};

struct m1m3_Actuators {
  long setpoint[M1M3NUMACT];	//	none : none : Force setpoint
  long position[M1M3NUMACT];	//	none : none : Position readback
  long error[M1M3NUMACT];	//	none : none : Error
  long status[M1M3NUMACT];	//	none : none : Status bits
  float cyltemp[M1M3NUMACT];	//	none : none : Cylinder temperature
  float envtemp[M1M3NUMACT];	//	none : none : Envir. temperature
  float lvdtcorr[M1M3NUMACT];	//	none : none : LVDT calibration adjustment
  float pressure[M1M3NUMACT];	//	none : none : Valve pressure
};


struct m1m3_ActuatorSample {
  unsigned short actuatorID;	//	none : none : Actuator id
  long setpoint[100];		//	none : none : Force setpoint
  long position[100];		//	none : none : Position readback
  long error[100];		//	none : none : Error
  long status[100];		//	none : none : Status bits
};

struct m1m3_LimitSensors {
  unsigned short liftoff[64];	//	none : none : Liftoff switches
  unsigned short limit[64];	//	none : none : Limit switches
};

struct m1m3_LUT {
  string<32> algorithm;		//	none :	none :	LUT interpolation algo.
  float param[32];		//	none :	none :	LUT parameters
};


struct m1m3_Electrical {
  long voltage[16];		//	none : none : Voltage
  long error[16];		//	none : none : Error
  unsigned short status[16];	//	none : none : Status bits
};

struct m1m3_TC {
  float setpoint[16];		//	none : none : Setpoint temp
  float temperature[16];	//	none : none : Measured temp
  float error[16];		//	none : none : Error
  unsigned short status[16];	//	none : none : Status bits
};

struct m1m3_Metrology {
  long distance[16];		//	none : none : Measured distance
  long error[16];		//	none : none : Error
  unsigned short status[16];	//	none : none : Status bits
};


struct m1m3_Application {
  float demand[6];		//	none : none : Target configuration
  float position[6];		//	none : none : Current value
  float error[6];		//	none : none : Target configuration
  unsigned short status[16];	//	none : none : Status bits
};



