struct scheduler_rankingData {
    long      observationNight;
    double    MJD;
    double    date;
    double    LST;
    long      fieldId;
    double    ra;
    double    dec;
    double    skyAngle;
    char      filter[32];
    double    exposureTime[10];
    double    mountAzimuth;
    double    mountAltitude;
    double    rotatorAngle;
    double    slewTime;
    double    visitTime;
    double    skyBrightnessV;
    double    skyBrightnessFilter;
    double    seeing;
    double    transparency;
    double    moonIllumination;
    double    moonRa;
    double    moonDec;
    double    moonAlt;
    double    moonAz;
    double    moonDistance;
    double    sunAlt;
    double    sunAz;
    double    sunElongation;
    double    weatherWindSpeed;
    double    weatherWindDirection;
    double    weatherHumidity;
}

