struct tcs_kernel_TrackRefSys {
  float tdbj;
  float amprms[21];
  float ae2mt[9];
  float hm;
  float tlat;
  float diurab;
  float refa;
  float refb;
  float temp;
  float press;
  float humid;
  float tlr;
  float wavel;
  float sst;
  float cst;
};
