struct tcs_kernel_Site {
  float tai;
  float delat;
  float delut;
  float ttmtat;
  float elongm;
  float latm;
  float hm;
  float xpm;
  float ypm;
  float Ttmtai;
  float Elong;
  float Lat;
  float Uau;
  float Vau;
  float Ukm;
  float Vkm;
  float Diurab;
  float T0;
  float St0;
  float Tt0;
  float Ttj;
  float Amprms[21];
  float Aoprms[15];
  float Refa;
  float Refb;
  float Daz;
};
