struct enclosure_Application {




struct enclosure_Azimuth {
  long Raw[16];
  float Calibrated[32];
};




struct enclosure_Electrical {
  long Raw[16];
  float Calibrated[32];
};




struct enclosure_Metrology {
  long Raw[16];
  float Calibrated[16];
};




struct enclosure_Shutter {
  long Raw[16];
  float Calibrated[32];
};




struct enclosure_TC {
  long Raw[16];
  float Calibrated[16];
};




struct enclosure_Thermal_control {
  long Raw[16];
  float Calibrated[32];
};




struct enclosure_Vents {
  long Raw[16];
  float Calibrated[32];
};




struct enclosure_command {
  long cmdID;
  string<16> device;
  string<16> operation;
  string<16> value;
  string<128> modifiers;
};




struct enclosure_response {
  long cmdID;
  string<16> ack;
  string<16> error;
  long timeout;
  short repeat;
  short submits;
  string<64> result;
};




