/*
 * Please so not edit this file by hand!
 * This file was automatically generated by: nddsgen
 */

#include <rpc/types.h>
#include <rpc/xdr.h>
#include "rtControlState.h"


bool_t
xdr_rtControlStateStruct(XDR *xdrs, rtControlStateStruct *objp)
{
	if (!xdr_char(xdrs, &objp->rtDrivingMode)) {
		return (FALSE);
	}
	if (!xdr_char(xdrs, &objp->rtHeartbeatMask)) {
		return (FALSE);
	}
	if (!xdr_char(xdrs, &objp->rtWatchdogMask)) {
		return (FALSE);
	}
	if (!xdr_char(xdrs, &objp->rtCommand)) {
		return (FALSE);
	}
	return (TRUE);
}


