/*
 * Please so not edit this file by hand!
 * This file was automatically generated by: nddsgen
 */

#include <rpc/types.h>
#include <rpc/xdr.h>
#include "apsDerivedState.h"


bool_t
xdr_apsDerivedStateStruct(XDR *xdrs, apsDerivedStateStruct *objp)
{
	if (!xdr_int(xdrs, &objp->azimuth)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->elevation)) {
		return (FALSE);
	}
	if (!xdr_u_int(xdrs, &objp->msecs)) {
		return (FALSE);
	}
	if (!xdr_u_int(xdrs, &objp->week)) {
		return (FALSE);
	}
	return (TRUE);
}


