/*
 * Please so not edit this file by hand!
 * This file was automatically generated by: nddsgen
 */

#include <rpc/types.h>
#include <rpc/xdr.h>
#include "epsDerivedState.h"


bool_t
xdr_epsDerivedStateStruct(XDR *xdrs, epsDerivedStateStruct *objp)
{
	if (!xdr_u_int(xdrs, &objp->genFuel)) {
		return (FALSE);
	}
	if (!xdr_u_int(xdrs, &objp->upsCharge)) {
		return (FALSE);
	}
	if (!xdr_u_long(xdrs, &objp->upsLastTrigger)) {
		return (FALSE);
	}
	if (!xdr_u_long(xdrs, &objp->upsStateMask)) {
		return (FALSE);
	}
	if (!xdr_u_int(xdrs, &objp->msecs)) {
		return (FALSE);
	}
	if (!xdr_u_int(xdrs, &objp->week)) {
		return (FALSE);
	}
	return (TRUE);
}


