/*
 * Please so not edit this file by hand!
 * This file was automatically generated by: nddsgen
 */

#include <rpc/types.h>
#include <rpc/xdr.h>
#include "imuRawState.h"


bool_t
xdr_imuRawStateStruct(XDR *xdrs, imuRawStateStruct *objp)
{
	if (!xdr_vector(xdrs, (char *)objp->rotDotVolts, 3, sizeof(int), xdr_int)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->transDotDotVolts, 3, sizeof(int), xdr_int)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->tempVolts)) {
		return (FALSE);
	}
	if (!xdr_u_int(xdrs, &objp->msecs)) {
		return (FALSE);
	}
	if (!xdr_u_int(xdrs, &objp->week)) {
		return (FALSE);
	}
	return (TRUE);
}


