/*
 * Please so not edit this file by hand!
 * This file was automatically generated by: nddsgen
 */

#include <rpc/types.h>
#include <rpc/xdr.h>
#include "lasHazardMap.h"


bool_t
xdr_lasHazardMapStruct(XDR *xdrs, lasHazardMapStruct *objp)
{
	if (!xdr_vector(xdrs, (char *)objp->depthMap, 361, sizeof(int), xdr_int)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->enable)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->detect)) {
		return (FALSE);
	}
	if (!xdr_u_int(xdrs, &objp->msecs)) {
		return (FALSE);
	}
	if (!xdr_u_int(xdrs, &objp->week)) {
		return (FALSE);
	}
	return (TRUE);
}


