/*
 * Please so not edit this file by hand!
 * This file was automatically generated by: nddsgen
 */

#include <rpc/types.h>
#include <rpc/xdr.h>
#include "posDerivedState.h"


bool_t
xdr_posDerivedStateStruct(XDR *xdrs, posDerivedStateStruct *objp)
{
	if (!xdr_int(xdrs, &objp->posNorth)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->posWest)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->posUp)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->rotZ)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->rotY)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->rotX)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->posNorthDot)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->posWestDot)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->deltaUpDot)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->rotZDot)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->rotYDot)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->rotXDot)) {
		return (FALSE);
	}
	if (!xdr_u_int(xdrs, &objp->msecs)) {
		return (FALSE);
	}
	if (!xdr_u_int(xdrs, &objp->week)) {
		return (FALSE);
	}
	return (TRUE);
}


