/*
 * Please so not edit this file by hand!
 * This file was automatically generated by: nddsgen
 */

#include <rpc/types.h>
#include <rpc/xdr.h>
#include "posRawState.h"


bool_t
xdr_posRawStateStruct(XDR *xdrs, posRawStateStruct *objp)
{
	if (!xdr_vector(xdrs, (char *)objp->kalmanGain, 100, sizeof(float), xdr_float)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->gpsPosCovar, 9, sizeof(float), xdr_float)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->gpsRotCovar, 9, sizeof(float), xdr_float)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->compassRotCovar, 9, sizeof(float), xdr_float)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->imuRotCovar, 9, sizeof(float), xdr_float)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->imuPosCovar, 9, sizeof(float), xdr_float)) {
		return (FALSE);
	}
	if (!xdr_u_int(xdrs, &objp->msecs)) {
		return (FALSE);
	}
	if (!xdr_u_int(xdrs, &objp->week)) {
		return (FALSE);
	}
	return (TRUE);
}


