#!/usr/bin/tclsh

proc printformdata { } {
global env FormData
   foreach i [lsort [array names env]] {
       puts stdout "Env $i = $env($i)<BR>"
  }
   foreach i [lsort [array names FormData]] {
       puts stdout "Form $i = $FormData($i)<BR>"
  }
}

set OPDIR salvm

source /usr/local/scripts/tcl/GetPostedData.tcl
if { [info exists FormData(DEBUG)] == 0 } {set FormData(DEBUG) 0}
GetPostedData
puts stdout "Content-type: text/html\n\n"
if { $FormData(DEBUG) == 1 } {
  puts stdout "<HTML><HEAD></HEAD><BODY>"
  printformdata
}

exec mv /var/www/html/$OPDIR/index.html /var/www/html/$OPDIR/oldindex.html
set fout [open /var/www/html/$OPDIR/index.html w]
puts $fout "
<HTML><HEAD><TITLE>SAL VM workbench configuration</TITLE></HEAD>
<BODY BGCOLOR=White>
<IMG SRC=\"/LSST_logo.gif\" ALIGN=CENTER>
<IMG SRC=\"salwbconfig.gif\" ALIGN=CENTER><P><HR><P>
<H1>Introduction</H1><P>
This form provides configuration options for the LSST SAL 
VM workbench. <BR>
The SAL VM provides an environment for
LSST software developers to specify inter-subsystem 
interfaces and generate compliant code.<P>

Each instance of the VM should be associated with a single
developer. To alter the information associated with this VM 
modify this form and click the 
\"Change Registration\" button.<P>

<FORM method=\"post\" action=\"/cgi-bin/register\">
Name : <INPUT TYPE=\"TEXT\" SIZE=40 NAME=\"username\" VALUE=\"$FormData(username)\"><BR>
Organization : <INPUT TYPE=\"TEXT\"  SIZE=40 NAME=\"organization\" VALUE=\"$FormData(organization)\"><BR>
Email : <INPUT TYPE=\"TEXT\"  SIZE=40 NAME=\"email\" VALUE=\"$FormData(email)\"><BR>
<P>
Autoupgrade SAL VM to latest release on each restart : <SELECT NAME=\"autoupgrade\">"

if { $FormData(autoupgrade) == "YES" } {
  puts $fout "
<OPTION VALUE=\"YES\" SELECTED>Yes
<OPTION VALUE=\"NO\"> No"
  exec touch /home/saluser/.autoupgrade
} else {
  puts $fout "
<OPTION VALUE=\"YES\">Yes
<OPTION VALUE=\"NO\" SELECTED> No"
  exec rm /home/saluser/.autoupgrade
}

puts $fout "
<OPTION VALUE=\"YES\" SELECTED>Yes
<OPTION VALUE=\"NO\"> No
</SELECT>
<P>
<input type=\"submit\" value=\"Change Registeration\"></FORM>
<HR>
<H1>Workbench tasks</H1>
<A HREF=\"/streams/index.html\">Create and modify Telemetry Datastream Definitions</A><BR>
Create and modify subsystem Command sets (TBD)<BR>
<HR>
</BODY></HTML>"

close $fout 

puts stdout "<HTML><HEAD><META HTTP-EQUIV=\"Refresh\" CONTENT=\"5; URL=http://$env(HTTP_HOST)/$OPDIR/index.html\"></HEAD><BODY>
<H1>Registering.....please wait</H1></BODY></HTML>"
exit
