module seeing
{
	struct dimm_Application {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  long	Raw[16];
	  float	Calibrated[32];
	  float	Error[4];
	  string<16>	Status;
	};
	#pragma keylist dimm_Application
	struct dimm_Electrical {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  long	Raw[16];
	  float	Calibrated[31];
	  octet	Status[15];
	};
	#pragma keylist dimm_Electrical
	struct dimm_Measurement {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  long	hrnum;
	  string<16>	utdate;
	  string<16>	uttime;
	  float	exposure;
	  long	numlines;
	  float	seeing_corr;
	  long	flux;
	  float	scintleft;
	  float	scintright;
	  float	strehlleft;
	  float	strehlright;
	};
	#pragma keylist dimm_Measurement
	struct dimm_Metrology {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  long	Raw[16];
	  float	Calibrated[15];
	  octet	Limits[63];
	  octet	Status[63];
	};
	#pragma keylist dimm_Metrology
	struct dimm_TC {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  long	Raw[16];
	  float	Calibrated[16];
	};
	#pragma keylist dimm_TC
	struct dimm_Temps {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  long	Raw[15];
	  float	Calibrated[15];
	  octet	Health[15];
	};
	#pragma keylist dimm_Temps
	struct mass_Application {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  float	Demand[2];
	  float	Position[2];
	  float	Error[2];
	  string<128>	Status_1;
	  string<128>	Status_2;
	  string<128>	Status_3;
	  string<128>	Status_4;
	  string<128>	Status_5;
	  string<128>	Status_6;
	  string<128>	Status_7;
	  string<128>	Status_8;
	  string<128>	Status_9;
	  string<128>	Status_10;
	  string<128>	Status_11;
	  string<128>	Status_12;
	  string<128>	Status_13;
	  string<128>	Status_14;
	  string<128>	Status_15;
	};
	#pragma keylist mass_Application
	struct mass_Electrical {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  long	Raw[16];
	  float	Calibrated[32];
	};
	#pragma keylist mass_Electrical
	struct mass_Metrology {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  long	Raw[16];
	  float	Calibrated[16];
	  octet	Limits[63];
	  octet	Status[63];
	};
	#pragma keylist mass_Metrology
	struct mass_TC {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  long	Raw[16];
	  float	Calibrated[16];
	};
	#pragma keylist mass_TC
	struct mass_Temps {
	  string<32> private_revCode;  //private
	  double     private_sndStamp; //private
	  double     private_rcvStamp; //private
	  long       private_seqNum;   //private
	  long       private_origin;   //private
	  long	Raw[15];
	  float	Calibrated[15];
	  octet	Health[15];
	};
	#pragma keylist mass_Temps
};
