struct camera_Cryo_pressure {
  string<32> private_revCode;  //private
  double     private_sndStamp; //private
  double     private_rcvStamp; //private
  long       private_seqNum;   //private
  long       private_origin;   //private
  float	Intake_pressure[2];	// 0.010 | Pa | Compressor intake  pressure | none | Utility room | 2 | 864  | 3,456 
  float	Pre_expansion_pressure[2];	// 0.010 | Pa | Pre-expansion C4 pressure | none | Cryostat or utility trunk | 2 | 864  | 3,456 
  float	Post_expansion_pressure[2];	// 0.010 | Pa | Post-evaporator pressure | none | Cryostat or utility trunk | 2 | 864  | 3,456 
};
#pragma keylist camera_Cryo_pressure 
