struct WDS_status {
  string<32> private_revCode;  //private
  double     private_sndStamp; //private
  double     private_rcvStamp; //private
  long       private_seqNum;   //private
  long       private_origin;   //private
  none	flag[20];	// 0.054 | none | Error flags[ | Science and corner rafts | 160 |  373,622  |  1,494,486  | 
  unsigned short	REB_ID;	// none | | Raft Electronics Board ID
};
#pragma keylist WDS_status
