struct camera_GAS {
  string<32> private_revCode;  //private
  double     private_sndStamp; //private
  double     private_rcvStamp; //private
  long       private_seqNum;   //private
  long       private_origin;   //private
  string<32>	algorithm;
  float	parameters[10];
  float	sampleData_00[25];
  float	sampleData_01[25];
  float	sampleData_10[25];
  float	sampleData_11[25];
};
