struct camera_BEE_thermal {
  string<32> private_revCode;  //private
  long       private_sndStamp; //private
  long       private_rcvStamp; //private
  long       private_seqNum;   //private
  long       private_origin;   //private
  unsigned short raftID;	#	none ;	none ;	Raft Identification code
  float temp[20];		#	kelvin ; 0.0,200.0 ; Temperatures
  float heaterPower[10];	#	watt ;	0.0,10.0 ; Heater output power
  long  heaterStatus[10];	#	none ;	none ;	Heater status bits
  unsigned long cfgChkSum;	#	none ;	none ;	Configuration checksum
