struct Cold_current {
  string<32> private_revCode;  //private
  double     private_sndStamp; //private
  double     private_rcvStamp; //private
  long       private_seqNum;   //private
  long       private_origin;   //private
  float	Ion_pump[4];	// 0.010 | Amp | Ion pump current (3 cryostat, 1 heat exch) | none | Utility trunk | 4 |  1,728  |  6,912 
  float	Heater_current[6];	// 0.010 | Amp | Coldplate heater currents | none | Cryostat | 6 |  2,592  |  5,184 
};
#pragma keylist Cold_current
