struct camera_BEE_clocks {
  string<32> private_revCode;  //private
  long       private_sndStamp; //private
  long       private_rcvStamp; //private
  long       private_seqNum;   //private
  long       private_origin;   //private
  long	serial_1A[NUMCCD];	#	none ;	none ;	Serial clock voltage 1A raw value
  long	serial_2A[NUMCCD];	#	none ;	none ;	Serial clock voltage 2A raw value
  long	serial_3A[NUMCCD];	#	none ;	none ;	Serial clock voltage 3A raw value
  long	serial_1B[NUMCCD];	#	none ;	none ;	Serial clock voltage 1B raw value
  long	serial_2B[NUMCCD];	#	none ;	none ;	Serial clock voltage 2B raw value
  long	serial_3B[NUMCCD];	#	none ;	none ;	Serial clock voltage 3B raw value
  long  parallel_1A[NUMCCD];	#	none ;	none ;	Parallel clock voltage 1A raw value
  long  parallel_1B[NUMCCD];	#	none ;	none ;	Parallel clock voltage 1B raw value
  long  parallel_2A[NUMCCD];	#	none ;	none ;	Parallel clock voltage 2A raw value
  long  parallel_2B[NUMCCD];	#	none ;	none ;	Parallel clock voltage 2B raw value
