struct camera_BEE_thermal {
  string<32> private_revCode;  //private
  double     private_sndStamp; //private
  double     private_rcvStamp; //private
  long       private_seqNum;   //private
  long       private_origin;   //private
  unsigned short	raftID;
  float	temp[20];
  float	heaterPower[10];
  long	heaterStatus[10];
  unsigned long	cfgChkSum;
};
