struct camera_CALSYS {
  string<32> private_revCode;  //private
  long       private_sndStamp; //private
  long       private_rcvStamp; //private
  long       private_seqNum;   //private
  long       private_origin;   //private
  float profile [1024];		#	none ;	none ;	Motion profile during calibration run 
