struct Filter_voltage {
  string<32> private_revCode;  //private
  double     private_sndStamp; //private
  double     private_rcvStamp; //private
  long       private_seqNum;   //private
  long       private_origin;   //private
  float	Latch_voltage[10];	// 2.31E-04 | Volt | Carousel: 10 actuator voltages | none | Camera body | 10 |  100  |  400 
  float	Clamp_voltage[5];	// 2.31E-04 | Volt | Auto: Actuator voltages | none | Camera body | 5 |  50  |  200 
};
#pragma keylist Filter_voltage
