struct Purge_flow {
  string<32> private_revCode;  //private
  double     private_sndStamp; //private
  double     private_rcvStamp; //private
  long       private_seqNum;   //private
  long       private_origin;   //private
  float	Flow_meter;	// 0.017 | lps | Flow meters |  | Utility trunk | ?? | ?? | ??
  float	Flow_meter;	// 0.017 | lps | Flow meters |  | Camera body | ?? | ?? | ??
};
#pragma keylist Purge_flow
