struct camera_UTIL {
  string<32> private_revCode;  //private
  double     private_sndStamp; //private
  double     private_rcvStamp; //private
  long       private_seqNum;   //private
  long       private_origin;   //private
  float	flow_rate[10];
  float	temperature[10];
  float	setpoint[10];
  unsigned long	status[10];
};
