struct camera_WDS_wfsRaft {
  string<32> private_revCode;  //private
  long       private_sndStamp; //private
  long       private_rcvStamp; //private
  long       private_seqNum;   //private
  long       private_origin;   //private
  float parameters[32];		#	none ;	none ;	Control parameters
  float metrics[32];		#	none ;	none ;	Measured metrics
  float zernikes[16];		#	none ;	none ;	Measured zernikes
  unsigned long status;		#	none ;	none ;	Status flags
  string<128> avgInsideImage;	#	none ;	none ;	BLOB ref for inside focus average
  string<128> avgOutsideImage;	#	none ;	none ;	BLOB ref for outside focus average
  string<128> CalcImage1;	#	none ;	none ;	BLOB ref for reduced image 1 
  string<128> CalcImage2;	#	none ;	none ;	BLOB ref for reduced image 2
