struct camera_TC_zone2 {
  string<32> private_revCode;  //private
  double     private_sndStamp; //private
  double     private_rcvStamp; //private
  long       private_seqNum;   //private
  long       private_origin;   //private
  float	cold_plate[25];
  float	temperature[25];
  float	setpoint[25];
  long	status[25];
};
#pragma keylist camera_TC_zone2
