struct ructure_ {
  string<32> private_revCode;  //private
  double     private_sndStamp; //private
  double     private_rcvStamp; //private
  long       private_seqNum;   //private
  long       private_origin;   //private
  	No information;	//  |  |  |  |  |  |  | 
};
#pragma keylist ructure_
