struct m1m3_ActuatorSample {
  string<32> private_revCode;  //private
  long       private_sndStamp; //private
  long       private_rcvStamp; //private
  long       private_seqNum;   //private
  long       private_origin;   //private
  unsigned short actuatorID;	#	none ; none ; Actuator id
  long setpoint[100];		#	none ; none ; Force setpoint
  long position[100];		#	none ; none ; Position readback
  long error[100];		#	none ; none ; Error
  long status[100];		#	none ; none ; Status bits
};
