struct m1m3_Supports {
  string<32> private_revCode;  //private
  double     private_sndStamp; //private
  double     private_rcvStamp; //private
  long       private_seqNum;   //private
  long       private_origin;   //private
  long	targetpos[6];
  long	stepcnt[6];
  float	force[6];
};
