struct m1m3_Electrical {
  string<32> private_revCode;  //private
  long       private_sndStamp; //private
  long       private_rcvStamp; //private
  long       private_seqNum;   //private
  long       private_origin;   //private
  long voltage[16];		//	none : none : Voltage
  long error[16];		//	none : none : Error
  unsigned short status[16];	//	none : none : Status bits
};
