struct m1m3_Supports {
  string<32> private_revCode;  //private
  long       private_sndStamp; //private
  long       private_rcvStamp; //private
  long       private_seqNum;   //private
  long       private_origin;   //private
  long targetpos[6];		//	none : none : Stepper Motor target position
  long stepcnt[6];		//	none : none : Stepper Motor actual position
  float force[6];		//	none : none : Measured force
};
