struct m1m3_TC {
  string<32> private_revCode;  //private
  long       private_sndStamp; //private
  long       private_rcvStamp; //private
  long       private_seqNum;   //private
  long       private_origin;   //private
  float setpoint[16];		//	none : none : Setpoint temp
  float temperature[16];	//	none : none : Measured temp
  float error[16];		//	none : none : Error
  unsigned short status[16];	//	none : none : Status bits
};
