struct m2_Metrology {
  string<32> private_revCode;  //private
  long       private_sndStamp; //private
  long       private_rcvStamp; //private
  long       private_seqNum;   //private
  long       private_origin;   //private
  long distance[16];		#	none ; none ; Measured distance
  long error[16];		#	none ; none ; Error
  unsigned short status[16];	#	none ; none ; Status bits
};
