struct ocs_database_state {
  string<32> private_revCode;  //private
  double     private_sndStamp; //private
  double     private_rcvStamp; //private
  long       private_seqNum;   //private
  long       private_origin;   //private
  string<64>	name;
  string<64>	table;
  long	status[32];
  long	recin[32];
  long	recout[32];
  long	capacity[32];
  long	lastrep[32];
};
