struct ocs_system_accesscontrol {
  string<32> private_revCode;  //private
  double     private_sndStamp; //private
  double     private_rcvStamp; //private
  long       private_seqNum;   //private
  long       private_origin;   //private
  string<128>	subssystem;
  string<128>	device;
  string<500>	bystation;
  string<500>	byoperator;
  string<500>	bypolicy;
};
