//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: SALData.h
//  Source: ../idl/SALData.idl
//  Generated: Sun May 26 11:41:57 2013
//  OpenSplice V6.3.0
//  
//******************************************************************
#ifndef _SALDATA_H_
#define _SALDATA_H_

#include "sacpp_mapping.h"
#include "sacpp_DDS_DCPS.h"

namespace SALData
{
   struct SALTopic;

   struct SALTopic
   {
      DDS::String_mgr private_revCode;
      DDS::Double private_sndStamp;
      DDS::Double private_rcvStamp;
      DDS::Long private_origin;
   };

   typedef DDS_DCPSStruct_var < SALTopic> SALTopic_var;
   typedef DDS_DCPSStruct_out < SALTopic> SALTopic_out;
}




#endif 
