set COMMENT(tcs.kernel.TrackRefSys.tdbj) "None"
set COMMENT(tcs.kernel.TrackRefSys.amprms) "None"
set COMMENT(tcs.kernel.TrackRefSys.ae2mt) "None"
set COMMENT(tcs.kernel.TrackRefSys.hm) "None"
set COMMENT(tcs.kernel.TrackRefSys.tlat) "None"
set COMMENT(tcs.kernel.TrackRefSys.diurab) "None"
set COMMENT(tcs.kernel.TrackRefSys.refa) "None"
set COMMENT(tcs.kernel.TrackRefSys.refb) "None"
set COMMENT(tcs.kernel.TrackRefSys.temp) "None"
set COMMENT(tcs.kernel.TrackRefSys.press) "None"
set COMMENT(tcs.kernel.TrackRefSys.humid) "None"
set COMMENT(tcs.kernel.TrackRefSys.tlr) "None"
set COMMENT(tcs.kernel.TrackRefSys.wavel) "None"
set COMMENT(tcs.kernel.TrackRefSys.sst) "None"
set COMMENT(tcs.kernel.TrackRefSys.cst) "None"
set COMMENT(tcs.kernel.Target.site) "None"
set COMMENT(tcs.kernel.Target.t0) "None"
set COMMENT(tcs.kernel.Target.az) "None"
set COMMENT(tcs.kernel.Target.el) "None"
set COMMENT(tcs.kernel.Target.azdot) "None"
set COMMENT(tcs.kernel.Target.eldot) "None"
set COMMENT(tcs.kernel.Target.Wavel) " effective wavelength (microns)"
set COMMENT(tcs.kernel.Target.XOffset) " target offset"
set COMMENT(tcs.kernel.Target.YOffset) "None"
set COMMENT(tcs.kernel.Target.OffSys) " offset reference frame"
set COMMENT(tcs.kernel.Target.focalplaneX) " focal plane position"
set COMMENT(tcs.kernel.Target.focalplaneY) " focal plane position"
set COMMENT(tcs.kernel.Target.Temp) " temperature (deg K)"
set COMMENT(tcs.kernel.Target.Press) " pressure (mbar)"
set COMMENT(tcs.kernel.Target.Humid) " relative humidity"
set COMMENT(tcs.kernel.Target.TLR) " tropospheric lapse rate"
set COMMENT(tcs.kernel.Target.Tai) " TAI of last pointing calculation (MJD)"
set COMMENT(tcs.kernel.DawdleFilter.TunePar) " tuning parameter (maximum velocity)"
set COMMENT(tcs.kernel.DawdleFilter.Bypass) " bypass flag"
set COMMENT(tcs.kernel.DawdleFilter.T) " last time filter ran"
set COMMENT(tcs.kernel.FK5Target.ra) "None"
set COMMENT(tcs.kernel.FK5Target.dec) "None"
set COMMENT(tcs.kernel.FK5Target.equinox) "None"
set COMMENT(tcs.kernel.FK5Target.epoc) "None"
set COMMENT(tcs.kernel.FK5Target.pmRA) "None"
set COMMENT(tcs.kernel.FK5Target.pmDec) "None"
set COMMENT(tcs.kernel.FK5Target.parallax) "None"
set COMMENT(tcs.kernel.FK5Target.rv) "None"
set COMMENT(tcs.kernel.OpticsVt.tip) "None"
set COMMENT(tcs.kernel.OpticsVt.tilt) "None"
set COMMENT(tcs.kernel.PointingControl.RollFilter) " filter for roll axis"
set COMMENT(tcs.kernel.PointingControl.PitchFilter) " filter for pitch axis"
set COMMENT(tcs.kernel.PointingControl.AGuide) " guide correction in roll"
set COMMENT(tcs.kernel.PointingControl.BGuide) " guide correction in pitch"
set COMMENT(tcs.kernel.PointingControl.ALocal) " local correction in roll"
set COMMENT(tcs.kernel.PointingControl.BLocal) " local correction in pitch"
set COMMENT(tcs.kernel.PointingLog.Tai) " TAI (MJD) of obervation"
set COMMENT(tcs.kernel.PointingLog.Ra) " ICRF right ascension of observation (radians)"
set COMMENT(tcs.kernel.PointingLog.Dec) " ICRF declination of observation (radians)"
set COMMENT(tcs.kernel.PointingLog.Wavel) " wavelength (microns)"
set COMMENT(tcs.kernel.PointingLog.Roll) " roll demand at Tai (radians)"
set COMMENT(tcs.kernel.PointingLog.Pitch) " pitch demand at Tai (radians)"
set COMMENT(tcs.kernel.PointingLog.Casspa) " cass equivalent rotator angle (radians)"
set COMMENT(tcs.kernel.PointingLog.Xr) " pointing origin X coordinate (mm)"
set COMMENT(tcs.kernel.PointingLog.Yr) " pointing origin Y coordinate (mm)"
set COMMENT(tcs.kernel.PointingLog.Fl) " focal length (mm)"
set COMMENT(tcs.kernel.PointingLog.Temp) " temperature (deg K)"
set COMMENT(tcs.kernel.PointingLog.Press) " pressure (mbar)"
set COMMENT(tcs.kernel.PointingLog.Humid) " relative Humidity"
set COMMENT(tcs.kernel.PointingLog.Tlr) " tropospheric lapse rate"
set COMMENT(tcs.kernel.PointingLog.Rcorr) " correction to rotator angle (radians)"
set COMMENT(tcs.kernel.PointingLog.Aux) " auxiliary readings"
set COMMENT(tcs.kernel.PointingLog.Marked) " data available flag"
set COMMENT(tcs.kernel.PointingModel.Model) " term numbers for current model"
set COMMENT(tcs.kernel.PointingModel.Coeffv) " coefficient value"
set COMMENT(tcs.kernel.PointingModel.Nterml) " number of local terms"
set COMMENT(tcs.kernel.PointingModel.Ntermx) " number of terms implemented explicitly"
set COMMENT(tcs.kernel.PointingModel.Nterms) " number of terms available currently"
set COMMENT(tcs.kernel.PointingModel.Coeff1) " coefficient names"
set COMMENT(tcs.kernel.PointingModel.Coeff2) " coefficient names"
set COMMENT(tcs.kernel.PointingModel.Coeff3) " coefficient names"
set COMMENT(tcs.kernel.PointingModel.Coeff4) " coefficient names"
set COMMENT(tcs.kernel.PointingModel.Coeff5) " coefficient names"
set COMMENT(tcs.kernel.PointingModel.Coeff6) " coefficient names"
set COMMENT(tcs.kernel.PointingModel.Coeff7) " coefficient names"
set COMMENT(tcs.kernel.PointingModel.Coeff8) " coefficient names"
set COMMENT(tcs.kernel.PointingModel.Coeff9) " coefficient names"
set COMMENT(tcs.kernel.PointingModel.Cofor1) " format of generic term"
set COMMENT(tcs.kernel.PointingModel.Cofor2) " format of generic term"
set COMMENT(tcs.kernel.PointingModel.Cofor3) " format of generic term"
set COMMENT(tcs.kernel.PointingModel.Cofor4) " format of generic term"
set COMMENT(tcs.kernel.PointingModel.Cofor5) " format of generic term"
set COMMENT(tcs.kernel.PointingModel.Cofor6) " format of generic term"
set COMMENT(tcs.kernel.PointingModel.Cofor7) " format of generic term"
set COMMENT(tcs.kernel.PointingModel.Cofor8) " format of generic term"
set COMMENT(tcs.kernel.PointingModel.Cofor9) " format of generic term"
set COMMENT(tcs.kernel.Site.tai) "None"
set COMMENT(tcs.kernel.Site.delat) "None"
set COMMENT(tcs.kernel.Site.delut) "None"
set COMMENT(tcs.kernel.Site.ttmtat) "None"
set COMMENT(tcs.kernel.Site.elongm) "None"
set COMMENT(tcs.kernel.Site.latm) "None"
set COMMENT(tcs.kernel.Site.hm) "None"
set COMMENT(tcs.kernel.Site.xpm) "None"
set COMMENT(tcs.kernel.Site.ypm) "None"
set COMMENT(tcs.kernel.Site.Delut) " UT1 - UTC (days)"
set COMMENT(tcs.kernel.Site.Delat) " TAI -UTC (days)"
set COMMENT(tcs.kernel.Site.Ttmtai) " TT - TAI (days)"
set COMMENT(tcs.kernel.Site.Elong) " corrected east longitude (radians)"
set COMMENT(tcs.kernel.Site.Lat) " corrected latitude (radians)"
set COMMENT(tcs.kernel.Site.Uau) " distance from spin axis (AU)"
set COMMENT(tcs.kernel.Site.Vau) " distance from equator (AU)"
set COMMENT(tcs.kernel.Site.Ukm) " distance from spin axis (km)"
set COMMENT(tcs.kernel.Site.Vkm) " distance from equator (km)"
set COMMENT(tcs.kernel.Site.Diurab) " diurnal aberration (radians)"
set COMMENT(tcs.kernel.Site.T0) " reference epoch TAI (MJD)"
set COMMENT(tcs.kernel.Site.St0) " reference siderial time (radians)"
set COMMENT(tcs.kernel.Site.Tt0) " reference time TT (MJD)"
set COMMENT(tcs.kernel.Site.Ttj) " reference time TT (Julian date)"
set COMMENT(tcs.kernel.Site.Amprms) " apparent to mean parameters"
set COMMENT(tcs.kernel.Site.Aoprms) " apparent to observed parameters"
set COMMENT(tcs.kernel.Site.Refa) " tan refraction constant"
set COMMENT(tcs.kernel.Site.Refb) " tan**3 refraction constant"
set COMMENT(tcs.kernel.Site.Daz) " daily motion"
set COMMENT(tcs.kernel.TimeKeeper.Tai) " time TAI (MJD)"
set COMMENT(tcs.kernel.TimeKeeper.Tt) " TT time at Tai (MJD)"
set COMMENT(tcs.kernel.TimeKeeper.Cst) " cosine of sidereal time"
set COMMENT(tcs.kernel.TimeKeeper.Sst) " sine of sidereal time"
set COMMENT(tcs.kernel.TimeKeeper.Dcst) " rate of change of Cst per sample interval"
set COMMENT(tcs.kernel.TimeKeeper.Dsst) " rate of change of Sst per sample interval"
set COMMENT(tcs.kernel.TrackingTarget.PositionX) " position in tracking frame"
set COMMENT(tcs.kernel.TrackingTarget.PositionY) " position in tracking frame"
set COMMENT(tcs.kernel.TrackingTarget.T0) " reference time"
set COMMENT(tcs.kernel.TrackingTarget.VelocityX) " tracking rate in tracking frame"
set COMMENT(tcs.kernel.TrackingTarget.VelocityY) " tracking rate in tracking frame"
