/*
 * Please so not edit this file by hand!
 * This file was automatically generated by: nddsgen
 */

#include <rpc/types.h>
#include <rpc/xdr.h>
#include "sciPanTilt.h"


bool_t
xdr_sciPanTiltStruct(XDR *xdrs, sciPanTiltStruct *objp)
{
	if (!xdr_float(xdrs, &objp->pan)) {
		return (FALSE);
	}
	if (!xdr_float(xdrs, &objp->tilt)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->posMode)) {
		return (FALSE);
	}
	return (TRUE);
}


