# -*- python -*-
from lsst.ts.sal.make_salpy_lib import make_salpy_lib

# generate SALPY libraries needed for unit tests
make_salpy_lib("Test")
make_salpy_lib("Script")

# In theory one could use a Builder or Command
# but there's no benefit because I don't know how to tell
# if exising SALPY libraries are current or need to be rebuilt
