struct tcs_kernel_Target {
  integer private_revCode; //private
  integer private_sndStamp; //private
  integer private_rcvStamp; //private
  integer private_seqNum; //private
  integer private_origin; //private
  string<32> site;
  float t0;
  float az;
  float el;
  float azdot;
  float eldot;
  float Wavel;
  float XOffset;
  float YOffset;
  string<32> OffSys;
  float focalplaneX;
  float focalplaneY;
  float Temp;
  float Press;
  float Humid;
  float TLR;
  float Tai;
};
