#!/usr/bin/tclsh

set ip [split [exec /sbin/ifconfig eth0] \n]
set n [lindex [lindex [split [lindex $ip 1] ":"] 1] 0]
set fout [open /etc/issue w]
puts $fout "LSST SAL Virtual Machine"
puts $fout ""
puts $fout "  This instance has an IP address of $n."
puts $fout ""
puts $fout "Please use your web browser to access the"
puts $fout "user interface at http://$n"
close $fout


