/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ImagePacket.h"

bool_t
xdr_ImagePacketStruct(xdrs, objp)
	XDR *xdrs;
	ImagePacketStruct *objp;
{
	if (!xdr_int(xdrs, &objp->row_len)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->packet_num)) {
		return (FALSE);
	}
	if (!xdr_bytes(xdrs, (char **)&objp->line_data.line_data_val, (u_int *)&objp->line_data.line_data_len, ~0)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->headerId)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->x1)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->y1)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->x2)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->y2)) {
		return (FALSE);
	}
	return (TRUE);
}
