#!/bin/sh

cd $SAL_WORK_DIR
echo "Updating XML in $SAL_WORK_DIR"
wget -nv https://github.com/lsst-ts/ts_xml/archive/master.zip -O master.zip
unzip -o master.zip
mv -v ts_xml-master/sal_interfaces/*/*.xml .
rm -fr ts_xml-master master.zip


