#!/usr/bin/tclsh

proc initializeefdtables { subsys } { 
global EFD_WORK_DIR
   foreach s $subsys {
      if { [file exists $EFD_WORK_DIR/sql/create-tables-[set subsys]] == 0 } {
         puts sdout "WARNING : No current table definition for $s"
         exit
      }
      set status [catch {exec mysql -u efduser --password=lssttest EFD < sql/create-tables-[set subsys]} result]
      puts stdout "Initializing tables for $subsys $result"

   }
}

set EFD_WORK_DIR $env(EFD_WORK_DIR)

initializeefdtables $argv


