#!/bin/sh

mkdir -p $SAL_WORK_DIR/salUtils/org/lsst/sal
cd $SAL_WORK_DIR/salUtils
cp $SAL_DIR/code/templates/salUtils.java org/lsst/sal/.
cp $SAL_DIR/code/templates/salUtils.c .
JAVAH="-I/etc/alternatives/java_sdk_openjdk/include -I/etc/alternatives/java_sdk_openjdk/include/linux"
javah org.lsst.sal.salUtils
cp org_lsst_sal_salUtils.h $SAL_WORK_DIR/include/.
gcc -g -o libsalUtils.so salUtils.c $JAVAH -fPIC -shared
cp libsalUtils.so $SAL_WORK_DIR/lib/.
cp $SAL_DIR/code/templates/salUtils.java .
javac salUtils.java
mkdir -p $SAL_WORK_DIR/lib/org/lsst/sal
cp org/lsst/sal/salUtils.class $SAL_WORK_DIR/lib/org/lsst/sal/.
cp $SAL_DIR/set-tai.c .
gcc -o set-tai -g set-tai.c -lc
cd $SAL_WORK_DIR
