#!/usr/bin/tclsh

proc errorExit { code msg } {
global FLOG
   puts stdout $msg
   puts $FLOG $msg
   exit $code
}

set basedir .
set Byte_Size [lindex $argv 0]
set Checksum [string trim [lindex $argv 1] "'"]
set Generator [string trim [lindex $argv 2] "'"]
set Mime [string trim [lindex $argv 3] "'"]
set URL [string trim [lindex $argv 4] "'"]
set Version  [lindex $argv 5]
set fname  [file tail $URL]
set destination  $basedir/$Generator/[join [split [exec date -I] "-"] "/"]
exec mkdir -p $destination
set FLOG [open $destination/LFO_processing.log a]

puts $FLOG "Retreiving LFO from $URL - $Mime ($Byte_Size bytes , checksum = $Checksum , Generator = $Generator - Version $Version)"
if { [file exists $destination/$fname] } {
    errorExit -2 "File already exists - not retreived"
}


catch { exec wget $URL } res
set fname  [file tail $URL]
if { [file exists $fname] } {
    if { [file size $fname] != $Byte_Size } {
        errorExit -3 "$URL retreival failed - incorrect size [file size $fname] != $Byte_Size "
    }
    set cc [exec md5sum < $fname]
    if { [lindex $cc 0] != $Checksum } {
        errorExit -4  "$URL retreival failed - incorrect checksum $cc != $Checksum"
    }
} else { 
    errorExit -5 "$URL retreival failed - $res"
}

exec mv $fname $destination/.
puts $FLOG "Sucessfully saved $URL at $destination/$fname"
set mtype [lindex [exec file --mime-type  $destination/$fname] 1]
if { $mtype != $Mime } {
   puts $FLOG "Warning : $URL mime type not verfiable $mtype != $Mime"
}

close $FLOG
exit 0

