
source $env(SAL_DIR)/add_system_dictionary.tcl
foreach i $SYSDIC(systems) {set FREQUENCY($i) 1}

set FREQUENCY(atMonochromator) 0.054
set FREQUENCY(atWhiteLight) 0.054
set FREQUENCY(auxscope.Electrical) 0.054
set FREQUENCY(auxscope.Metrology) 0.054
set FREQUENCY(auxscope.Spectrometer) 0.0003
set FREQUENCY(auxscope.TC) 0.054
set FREQUENCY(auxscope.TCS) 0.054
set FREQUENCY(calibrationSpectrometer) 0.054
set FREQUENCY(calibrationElectrometer) 0.054
set FREQUENCY(calibration.Electrical) 0.054
set FREQUENCY(calibration.Metrology) 0.054
set FREQUENCY(calibration.TC) 0.054
set FREQUENCY(camera.CCC.status) 11
set FREQUENCY(camera.Cluster.Encoder) 0.054
set FREQUENCY(camera.Cold) 11
set FREQUENCY(camera.Cryo) 11
set FREQUENCY(camera.Filter) 11
set FREQUENCY(camera.GAS) 10
set FREQUENCY(camera.GDS) 11
set FREQUENCY(camera.PCMS) 11
set FREQUENCY(camera.Prot) 11
set FREQUENCY(camera.Purge) 11
set FREQUENCY(camera.SAS) 11
set FREQUENCY(camera.SDS) 11
set FREQUENCY(camera.Shutter) 11
set FREQUENCY(camera.WAS) 11
set FREQUENCY(camera.WDS) 0.054
set FREQUENCY(dm.derived.dataquality) 0.054
set FREQUENCY(dm.derived.psf) 0.054
set FREQUENCY(dm.pointing.wcs) 0.054
set FREQUENCY(dm.raw.dataquality) 0.054
set FREQUENCY(dome.Application) 0.054
set FREQUENCY(domeADB) 10
set FREQUENCY(domeTHCS) 1
set FREQUENCY(domeLouvers) 1
set FREQUENCY(dome.CapacitorBank) 10
set FREQUENCY(domeAPS) 10
set FREQUENCY(dome.Metrology) 0.054
set FREQUENCY(domeLWS) 10
set FREQUENCY(domeMONCS) 10
set FREQUENCY(environment.Dust.monitor) 0.054
set FREQUENCY(environment.Electrical) 0.054
set FREQUENCY(environment.Lightning.detector) 0.054
set FREQUENCY(environment.Seismometer) 10
set FREQUENCY(environment.TC) 1
set FREQUENCY(environment.Video.cameras) 0.054
set FREQUENCY(environment.Weather) 1
set FREQUENCY(hexapod.Actuators) 20
set FREQUENCY(hexapod.Application) 0.054
set FREQUENCY(hexapod.Electrical) 0.054
set FREQUENCY(hexapod.LimitSensors) 0.054
set FREQUENCY(hexapod.Metrology) 0.054
set FREQUENCY(hexapod.TC) 1
set FREQUENCY(lasercal.Application) 0.054
set FREQUENCY(lasercal.Electrical) 0.054
set FREQUENCY(lasercal.TC) 1
set FREQUENCY(m1m3.ActuatorSample) 10
set FREQUENCY(m1m3.Actuators) 1
set FREQUENCY(m1m3.Application) 0.054
set FREQUENCY(m1m3.Electrical) 0.054
set FREQUENCY(m1m3.LUT) 0.054
set FREQUENCY(m1m3.LimitSensors) 0.054
set FREQUENCY(m1m3.Metrology) 0.054
set FREQUENCY(m1m3.Support) 1
set FREQUENCY(m1m3.Supports) 1
set FREQUENCY(m1m3.Surface) 1
set FREQUENCY(m1m3.TC) 1
set FREQUENCY(m2ms.Actuators) 10
set FREQUENCY(m2ms.Application) 0.054
set FREQUENCY(m2ms.Electrical) 0.054
set FREQUENCY(m2ms.LimitSensors) 0.054
set FREQUENCY(m2ms.Metrology) 0.054
set FREQUENCY(m2ms.Surface) 1
set FREQUENCY(m2ms.TC) 1
set FREQUENCY(MTMount.Alt) 20
set FREQUENCY(MTMount.Application) 0.054
set FREQUENCY(MTMount.Az) 20
set FREQUENCY(MTMount.Electrical) 0.054
set FREQUENCY(MTMount.Metrology) 0.054
set FREQUENCY(MTMount.Rotator) 20
set FREQUENCY(MTMount.TC) 1
set FREQUENCY(network.Application) 0.054
set FREQUENCY(ocs.activity.planning) 0.054
set FREQUENCY(ocs.activity.record) 0.054
set FREQUENCY(ocs.database.state) 0.054
set FREQUENCY(ocs.operator.log) 20
set FREQUENCY(ocs.pointing.wcs) 0.054
set FREQUENCY(ocs.scheduler.econstraints) 0.054
set FREQUENCY(ocs.scheduler.iconstraints) 0.054
set FREQUENCY(ocs.scheduler.parameters) 0.054
set FREQUENCY(ocs.scheduler.program) 0.054
set FREQUENCY(ocs.scheduler.progress) 0.054
set FREQUENCY(ocs.scheduler.targets) 0.054
set FREQUENCY(ocs.staticanalysis) 0.054
set FREQUENCY(ocs.system) 0.054
set FREQUENCY(ocs.system.accesscontrol) 0.054
set FREQUENCY(ocs.system.configuration) 0.054
set FREQUENCY(ocs.system.networking) 1
set FREQUENCY(power.Electrical) 1
set FREQUENCY(power.TC) 1
set FREQUENCY(power.UPSs) 1
set FREQUENCY(rotator) 20
set FREQUENCY(scheduler.Application) 0.054
set FREQUENCY(seeing.dimm.Application) 0.054
set FREQUENCY(seeing.dimm.Electrical) 0.054
set FREQUENCY(seeing.dimm.Measurement) 0.1
set FREQUENCY(seeing.dimm.Metrology) 0.054
set FREQUENCY(seeing.dimm.TC) 0.054
set FREQUENCY(seeing.dimm.Temps) 0.054
set FREQUENCY(seeing.mass.Application) 0.1
set FREQUENCY(seeing.mass.Electrical) 0.054
set FREQUENCY(seeing.mass.Metrology) 0.054
set FREQUENCY(seeing.mass.TC) 0.054
set FREQUENCY(seeing.mass.Temps) 0.054
set FREQUENCY(skycam.Application) 0.054
set FREQUENCY(skycam.Electrical) 0.054
set FREQUENCY(skycam.Metrology) 0.054
set FREQUENCY(skycam.TC) 0.054
set FREQUENCY(system.Command.history) 100
set FREQUENCY(system.Computer.status) 1
set FREQUENCY(system.Hardware.revision.history) 0.054
set FREQUENCY(system.Software.revision.history) 0.054
set FREQUENCY(tcs.kernel.DawdleFilter) 0.054
set FREQUENCY(tcs.kernel.FK5Target) 20
set FREQUENCY(tcs.kernel.OpticsVt) 20
set FREQUENCY(tcs.kernel.PointingControl) 0.054
set FREQUENCY(tcs.kernel.PointingLog) 20
set FREQUENCY(tcs.kernel.PointingModel) 0.054
set FREQUENCY(tcs.kernel.Site) 0.054
set FREQUENCY(tcs.kernel.Target) 20
set FREQUENCY(tcs.kernel.TimeKeeper) 20
set FREQUENCY(tcs.kernel.TrackRefSys) 0.054
set FREQUENCY(tcs.kernel.TrackingTarget) 20
