struct Cold_pressure {
  string<32> private_revCode;  //private
  double     private_sndStamp; //private
  double     private_rcvStamp; //private
  long       private_seqNum;   //private
  long       private_origin;   //private
  float	Intake_pressure[6];	// 0.010 | Pa | Compressor intake  pressure | none | Utility room | 6 |  2,592  |  10,368 
  float	Pre_expansion_pressure[6];	// 0.010 | Pa | Pre-expansion C4 pressure | none | Cryostat or utility trunk | 6 |  2,592  |  10,368 
  float	Post_expansion_pressure[6];	// 0.010 | Pa | Post-evaporator pressure | none | Cryostat or utility trunk | 6 |  2,592  |  10,368 
};
#pragma keylist Cold_pressure
