struct  {
  string<32> private_revCode;  //private
  double     private_sndStamp; //private
  double     private_rcvStamp; //private
  long       private_seqNum;   //private
  long       private_origin;   //private
  	Camera;	// 18 |  | OCS |  |  |  |  | 
  unsigned short	REB_ID;	// none | | Raft Electronics Board ID
};
#pragma keylist 
