struct ocs_scheduler_targets {
  string<32> private_revCode;  //private
  double     private_sndStamp; //private
  double     private_rcvStamp; //private
  long       private_seqNum;   //private
  long       private_origin;   //private
  double	ra[10];
  double	dec[10];
  double	catid[10];
  double	airmass[10];
  double	rotangle[10];
  long	filter[10];
  long	numexp[10];
};
