struct tcs_kernel_PointingControl {
  string<32> private_revCode;  //private
  double     private_sndStamp; //private
  double     private_rcvStamp; //private
  long       private_seqNum;   //private
  long       private_origin;   //private
  string<32>	RollFilter;
  string<32>	PitchFilter;
  float	AGuide;
  float	BGuide;
  float	ALocal;
  float	BLocal;
};
