/*
 * Please so not edit this file by hand!
 * This file was automatically generated by: nddsgen
 */

#include <rpc/types.h>
#include <rpc/xdr.h>
#include "navHeading.h"


bool_t
xdr_navHeadingStruct(XDR *xdrs, navHeadingStruct *objp)
{
	if (!xdr_float(xdrs, &objp->heading)) {
		return (FALSE);
	}
	if (!xdr_float(xdrs, &objp->range)) {
		return (FALSE);
	}
	if (!xdr_float(xdrs, &objp->speed)) {
		return (FALSE);
	}
	return (TRUE);
}


