/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class salTopicId {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected salTopicId(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(salTopicId obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        swigTopicIdJNI.delete_salTopicId(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public salTopicId(SWIGTYPE_p_std__string operation) {
    this(swigTopicIdJNI.new_salTopicId(SWIGTYPE_p_std__string.getCPtr(operation)), true);
  }

  public SWIGTYPE_p_svcRTN salTelemetry() {
    return new SWIGTYPE_p_svcRTN(swigTopicIdJNI.salTopicId_salTelemetry(swigCPtr, this), true);
  }

  public SWIGTYPE_p_svcRTN salConnect(SWIGTYPE_p_svcTID topicnumber, SWIGTYPE_p_std__string operation) {
    return new SWIGTYPE_p_svcRTN(swigTopicIdJNI.salTopicId_salConnect(swigCPtr, this, SWIGTYPE_p_svcTID.getCPtr(topicnumber), SWIGTYPE_p_std__string.getCPtr(operation)), true);
  }

  public SWIGTYPE_p_svcRTN reSynchronize() {
    return new SWIGTYPE_p_svcRTN(swigTopicIdJNI.salTopicId_reSynchronize(swigCPtr, this), true);
  }

  public SWIGTYPE_p_svcRTN publisher() {
    return new SWIGTYPE_p_svcRTN(swigTopicIdJNI.salTopicId_publisher(swigCPtr, this), true);
  }

  public SWIGTYPE_p_svcRTN subscriber() {
    return new SWIGTYPE_p_svcRTN(swigTopicIdJNI.salTopicId_subscriber(swigCPtr, this), true);
  }

  public SWIGTYPE_p_svcRTN getSample(SWIGTYPE_p_svcINT timeout) {
    return new SWIGTYPE_p_svcRTN(swigTopicIdJNI.salTopicId_getSample(swigCPtr, this, SWIGTYPE_p_svcINT.getCPtr(timeout)), true);
  }

  public SWIGTYPE_p_svcRTN putSample() {
    return new SWIGTYPE_p_svcRTN(swigTopicIdJNI.salTopicId_putSample(swigCPtr, this), true);
  }

  public SWIGTYPE_p_svcRTN shmInfo() {
    return new SWIGTYPE_p_svcRTN(swigTopicIdJNI.salTopicId_shmInfo(swigCPtr, this), true);
  }

  public SWIGTYPE_p_svcTIME getCurrentTime() {
    return new SWIGTYPE_p_svcTIME(swigTopicIdJNI.salTopicId_getCurrentTime(swigCPtr, this), true);
  }

  public SWIGTYPE_p_svcINT setDebug(SWIGTYPE_p_svcUINT level) {
    return new SWIGTYPE_p_svcINT(swigTopicIdJNI.salTopicId_setDebug(swigCPtr, this, SWIGTYPE_p_svcUINT.getCPtr(level)), true);
  }

  public SWIGTYPE_p_svcINT getDebug() {
    return new SWIGTYPE_p_svcINT(swigTopicIdJNI.salTopicId_getDebug(swigCPtr, this), true);
  }

  public SWIGTYPE_p_svcRTN getItem(SWIGTYPE_p_svcIID itemId, SWIGTYPE_p_svcSHORT value) {
    return new SWIGTYPE_p_svcRTN(swigTopicIdJNI.salTopicId_getItem__SWIG_0(swigCPtr, this, SWIGTYPE_p_svcIID.getCPtr(itemId), SWIGTYPE_p_svcSHORT.getCPtr(value)), true);
  }

  public SWIGTYPE_p_svcRTN getItem(SWIGTYPE_p_svcIID itemId, SWIGTYPE_p_svcUSHORT value) {
    return new SWIGTYPE_p_svcRTN(swigTopicIdJNI.salTopicId_getItem__SWIG_1(swigCPtr, this, SWIGTYPE_p_svcIID.getCPtr(itemId), SWIGTYPE_p_svcUSHORT.getCPtr(value)), true);
  }

  public SWIGTYPE_p_svcRTN getItem(SWIGTYPE_p_svcIID itemId, SWIGTYPE_p_svcINT value) {
    return new SWIGTYPE_p_svcRTN(swigTopicIdJNI.salTopicId_getItem__SWIG_2(swigCPtr, this, SWIGTYPE_p_svcIID.getCPtr(itemId), SWIGTYPE_p_svcINT.getCPtr(value)), true);
  }

  public SWIGTYPE_p_svcRTN getItem(SWIGTYPE_p_svcIID itemId, SWIGTYPE_p_svcUINT value) {
    return new SWIGTYPE_p_svcRTN(swigTopicIdJNI.salTopicId_getItem__SWIG_3(swigCPtr, this, SWIGTYPE_p_svcIID.getCPtr(itemId), SWIGTYPE_p_svcUINT.getCPtr(value)), true);
  }

  public SWIGTYPE_p_svcRTN getItem(SWIGTYPE_p_svcIID itemId, SWIGTYPE_p_svcFLT fvalue) {
    return new SWIGTYPE_p_svcRTN(swigTopicIdJNI.salTopicId_getItem__SWIG_4(swigCPtr, this, SWIGTYPE_p_svcIID.getCPtr(itemId), SWIGTYPE_p_svcFLT.getCPtr(fvalue)), true);
  }

  public SWIGTYPE_p_svcRTN getItem(SWIGTYPE_p_svcIID itemId, SWIGTYPE_p_svcDBL dvalue) {
    return new SWIGTYPE_p_svcRTN(swigTopicIdJNI.salTopicId_getItem__SWIG_5(swigCPtr, this, SWIGTYPE_p_svcIID.getCPtr(itemId), SWIGTYPE_p_svcDBL.getCPtr(dvalue)), true);
  }

  public SWIGTYPE_p_svcRTN getItem(SWIGTYPE_p_svcIID itemId, SWIGTYPE_p_svcSHORT value, SWIGTYPE_p_svcINT size) {
    return new SWIGTYPE_p_svcRTN(swigTopicIdJNI.salTopicId_getItem__SWIG_6(swigCPtr, this, SWIGTYPE_p_svcIID.getCPtr(itemId), SWIGTYPE_p_svcSHORT.getCPtr(value), SWIGTYPE_p_svcINT.getCPtr(size)), true);
  }

  public SWIGTYPE_p_svcRTN getItem(SWIGTYPE_p_svcIID itemId, SWIGTYPE_p_svcUSHORT value, SWIGTYPE_p_svcINT size) {
    return new SWIGTYPE_p_svcRTN(swigTopicIdJNI.salTopicId_getItem__SWIG_7(swigCPtr, this, SWIGTYPE_p_svcIID.getCPtr(itemId), SWIGTYPE_p_svcUSHORT.getCPtr(value), SWIGTYPE_p_svcINT.getCPtr(size)), true);
  }

  public SWIGTYPE_p_svcRTN getItem(SWIGTYPE_p_svcIID itemId, SWIGTYPE_p_svcINT value, SWIGTYPE_p_svcINT size) {
    return new SWIGTYPE_p_svcRTN(swigTopicIdJNI.salTopicId_getItem__SWIG_8(swigCPtr, this, SWIGTYPE_p_svcIID.getCPtr(itemId), SWIGTYPE_p_svcINT.getCPtr(value), SWIGTYPE_p_svcINT.getCPtr(size)), true);
  }

  public SWIGTYPE_p_svcRTN getItem(SWIGTYPE_p_svcIID itemId, SWIGTYPE_p_svcUINT value, SWIGTYPE_p_svcINT size) {
    return new SWIGTYPE_p_svcRTN(swigTopicIdJNI.salTopicId_getItem__SWIG_9(swigCPtr, this, SWIGTYPE_p_svcIID.getCPtr(itemId), SWIGTYPE_p_svcUINT.getCPtr(value), SWIGTYPE_p_svcINT.getCPtr(size)), true);
  }

  public SWIGTYPE_p_svcRTN getItem(SWIGTYPE_p_svcIID itemId, SWIGTYPE_p_svcFLT fvalue, SWIGTYPE_p_svcINT size) {
    return new SWIGTYPE_p_svcRTN(swigTopicIdJNI.salTopicId_getItem__SWIG_10(swigCPtr, this, SWIGTYPE_p_svcIID.getCPtr(itemId), SWIGTYPE_p_svcFLT.getCPtr(fvalue), SWIGTYPE_p_svcINT.getCPtr(size)), true);
  }

  public SWIGTYPE_p_svcRTN getItem(SWIGTYPE_p_svcIID itemId, SWIGTYPE_p_svcDBL dvalue, SWIGTYPE_p_svcINT size) {
    return new SWIGTYPE_p_svcRTN(swigTopicIdJNI.salTopicId_getItem__SWIG_11(swigCPtr, this, SWIGTYPE_p_svcIID.getCPtr(itemId), SWIGTYPE_p_svcDBL.getCPtr(dvalue), SWIGTYPE_p_svcINT.getCPtr(size)), true);
  }

  public SWIGTYPE_p_svcRTN getItemStr(SWIGTYPE_p_svcIID itemId, SWIGTYPE_p_svcCHAR textValue) {
    return new SWIGTYPE_p_svcRTN(swigTopicIdJNI.salTopicId_getItemStr(swigCPtr, this, SWIGTYPE_p_svcIID.getCPtr(itemId), SWIGTYPE_p_svcCHAR.getCPtr(textValue)), true);
  }

  public SWIGTYPE_p_svcRTN setItem(SWIGTYPE_p_svcIID itemId, SWIGTYPE_p_svcSHORT value) {
    return new SWIGTYPE_p_svcRTN(swigTopicIdJNI.salTopicId_setItem__SWIG_0(swigCPtr, this, SWIGTYPE_p_svcIID.getCPtr(itemId), SWIGTYPE_p_svcSHORT.getCPtr(value)), true);
  }

  public SWIGTYPE_p_svcRTN setItem(SWIGTYPE_p_svcIID itemId, SWIGTYPE_p_svcUSHORT value) {
    return new SWIGTYPE_p_svcRTN(swigTopicIdJNI.salTopicId_setItem__SWIG_1(swigCPtr, this, SWIGTYPE_p_svcIID.getCPtr(itemId), SWIGTYPE_p_svcUSHORT.getCPtr(value)), true);
  }

  public SWIGTYPE_p_svcRTN setItem(SWIGTYPE_p_svcIID itemId, SWIGTYPE_p_svcINT value) {
    return new SWIGTYPE_p_svcRTN(swigTopicIdJNI.salTopicId_setItem__SWIG_2(swigCPtr, this, SWIGTYPE_p_svcIID.getCPtr(itemId), SWIGTYPE_p_svcINT.getCPtr(value)), true);
  }

  public SWIGTYPE_p_svcRTN setItem(SWIGTYPE_p_svcIID itemId, SWIGTYPE_p_svcUINT value) {
    return new SWIGTYPE_p_svcRTN(swigTopicIdJNI.salTopicId_setItem__SWIG_3(swigCPtr, this, SWIGTYPE_p_svcIID.getCPtr(itemId), SWIGTYPE_p_svcUINT.getCPtr(value)), true);
  }

  public SWIGTYPE_p_svcRTN setItem(SWIGTYPE_p_svcIID itemId, SWIGTYPE_p_svcFLT fvalue) {
    return new SWIGTYPE_p_svcRTN(swigTopicIdJNI.salTopicId_setItem__SWIG_4(swigCPtr, this, SWIGTYPE_p_svcIID.getCPtr(itemId), SWIGTYPE_p_svcFLT.getCPtr(fvalue)), true);
  }

  public SWIGTYPE_p_svcRTN setItem(SWIGTYPE_p_svcIID itemId, SWIGTYPE_p_svcDBL dvalue) {
    return new SWIGTYPE_p_svcRTN(swigTopicIdJNI.salTopicId_setItem__SWIG_5(swigCPtr, this, SWIGTYPE_p_svcIID.getCPtr(itemId), SWIGTYPE_p_svcDBL.getCPtr(dvalue)), true);
  }

  public SWIGTYPE_p_svcRTN setItem(SWIGTYPE_p_svcIID itemId, SWIGTYPE_p_svcSHORT value, SWIGTYPE_p_svcINT size) {
    return new SWIGTYPE_p_svcRTN(swigTopicIdJNI.salTopicId_setItem__SWIG_6(swigCPtr, this, SWIGTYPE_p_svcIID.getCPtr(itemId), SWIGTYPE_p_svcSHORT.getCPtr(value), SWIGTYPE_p_svcINT.getCPtr(size)), true);
  }

  public SWIGTYPE_p_svcRTN setItem(SWIGTYPE_p_svcIID itemId, SWIGTYPE_p_svcUSHORT value, SWIGTYPE_p_svcINT size) {
    return new SWIGTYPE_p_svcRTN(swigTopicIdJNI.salTopicId_setItem__SWIG_7(swigCPtr, this, SWIGTYPE_p_svcIID.getCPtr(itemId), SWIGTYPE_p_svcUSHORT.getCPtr(value), SWIGTYPE_p_svcINT.getCPtr(size)), true);
  }

  public SWIGTYPE_p_svcRTN setItem(SWIGTYPE_p_svcIID itemId, SWIGTYPE_p_svcINT value, SWIGTYPE_p_svcINT size) {
    return new SWIGTYPE_p_svcRTN(swigTopicIdJNI.salTopicId_setItem__SWIG_8(swigCPtr, this, SWIGTYPE_p_svcIID.getCPtr(itemId), SWIGTYPE_p_svcINT.getCPtr(value), SWIGTYPE_p_svcINT.getCPtr(size)), true);
  }

  public SWIGTYPE_p_svcRTN setItem(SWIGTYPE_p_svcIID itemId, SWIGTYPE_p_svcUINT value, SWIGTYPE_p_svcINT size) {
    return new SWIGTYPE_p_svcRTN(swigTopicIdJNI.salTopicId_setItem__SWIG_9(swigCPtr, this, SWIGTYPE_p_svcIID.getCPtr(itemId), SWIGTYPE_p_svcUINT.getCPtr(value), SWIGTYPE_p_svcINT.getCPtr(size)), true);
  }

  public SWIGTYPE_p_svcRTN setItem(SWIGTYPE_p_svcIID itemId, SWIGTYPE_p_svcFLT fvalue, SWIGTYPE_p_svcINT size) {
    return new SWIGTYPE_p_svcRTN(swigTopicIdJNI.salTopicId_setItem__SWIG_10(swigCPtr, this, SWIGTYPE_p_svcIID.getCPtr(itemId), SWIGTYPE_p_svcFLT.getCPtr(fvalue), SWIGTYPE_p_svcINT.getCPtr(size)), true);
  }

  public SWIGTYPE_p_svcRTN setItem(SWIGTYPE_p_svcIID itemId, SWIGTYPE_p_svcDBL dvalue, SWIGTYPE_p_svcINT size) {
    return new SWIGTYPE_p_svcRTN(swigTopicIdJNI.salTopicId_setItem__SWIG_11(swigCPtr, this, SWIGTYPE_p_svcIID.getCPtr(itemId), SWIGTYPE_p_svcDBL.getCPtr(dvalue), SWIGTYPE_p_svcINT.getCPtr(size)), true);
  }

  public SWIGTYPE_p_svcRTN setItemStr(SWIGTYPE_p_svcIID itemId, SWIGTYPE_p_svcCHAR textValue) {
    return new SWIGTYPE_p_svcRTN(swigTopicIdJNI.salTopicId_setItemStr(swigCPtr, this, SWIGTYPE_p_svcIID.getCPtr(itemId), SWIGTYPE_p_svcCHAR.getCPtr(textValue)), true);
  }

  public SWIGTYPE_p_svcRTN getProperty(SWIGTYPE_p_svcCHAR propertyName, SWIGTYPE_p_svcCHAR textValue) {
    return new SWIGTYPE_p_svcRTN(swigTopicIdJNI.salTopicId_getProperty(swigCPtr, this, SWIGTYPE_p_svcCHAR.getCPtr(propertyName), SWIGTYPE_p_svcCHAR.getCPtr(textValue)), true);
  }

  public SWIGTYPE_p_svcRTN setProperty(SWIGTYPE_p_svcCHAR propertyName, SWIGTYPE_p_svcCHAR textValue) {
    return new SWIGTYPE_p_svcRTN(swigTopicIdJNI.salTopicId_setProperty(swigCPtr, this, SWIGTYPE_p_svcCHAR.getCPtr(propertyName), SWIGTYPE_p_svcCHAR.getCPtr(textValue)), true);
  }

  public void setM_TopicId_shmid(int value) {
    swigTopicIdJNI.salTopicId_m_TopicId_shmid_set(swigCPtr, this, value);
  }

  public int getM_TopicId_shmid() {
    return swigTopicIdJNI.salTopicId_m_TopicId_shmid_get(swigCPtr, this);
  }

  public static void setM_shmMapper(SWIGTYPE_p_shmMapper value) {
    swigTopicIdJNI.salTopicId_m_shmMapper_set(SWIGTYPE_p_shmMapper.getCPtr(value));
  }

  public static SWIGTYPE_p_shmMapper getM_shmMapper() {
    return new SWIGTYPE_p_shmMapper(swigTopicIdJNI.salTopicId_m_shmMapper_get(), true);
  }

}
