/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


class svcSAL_TopicIdJNI {
  public final static native long new_uShortArray(int jarg1);
  public final static native void delete_uShortArray(long jarg1);
  public final static native int uShortArray_getitem(long jarg1, uShortArray jarg1_, int jarg2);
  public final static native void uShortArray_setitem(long jarg1, uShortArray jarg1_, int jarg2, int jarg3);
  public final static native long uShortArray_cast(long jarg1, uShortArray jarg1_);
  public final static native long uShortArray_frompointer(long jarg1);
}
