/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


class swigTopicIdJNI {
  public final static native long new_salTopicId(long jarg1);
  public final static native void delete_salTopicId(long jarg1);
  public final static native long salTopicId_salTelemetry(long jarg1, salTopicId jarg1_);
  public final static native long salTopicId_salConnect(long jarg1, salTopicId jarg1_, long jarg2, long jarg3);
  public final static native long salTopicId_reSynchronize(long jarg1, salTopicId jarg1_);
  public final static native long salTopicId_publisher(long jarg1, salTopicId jarg1_);
  public final static native long salTopicId_subscriber(long jarg1, salTopicId jarg1_);
  public final static native long salTopicId_getSample(long jarg1, salTopicId jarg1_, long jarg2);
  public final static native long salTopicId_putSample(long jarg1, salTopicId jarg1_);
  public final static native long salTopicId_shmInfo(long jarg1, salTopicId jarg1_);
  public final static native long salTopicId_getCurrentTime(long jarg1, salTopicId jarg1_);
  public final static native long salTopicId_setDebug(long jarg1, salTopicId jarg1_, long jarg2);
  public final static native long salTopicId_getDebug(long jarg1, salTopicId jarg1_);
  public final static native long salTopicId_getItem__SWIG_0(long jarg1, salTopicId jarg1_, long jarg2, long jarg3);
  public final static native long salTopicId_getItem__SWIG_1(long jarg1, salTopicId jarg1_, long jarg2, long jarg3);
  public final static native long salTopicId_getItem__SWIG_2(long jarg1, salTopicId jarg1_, long jarg2, long jarg3);
  public final static native long salTopicId_getItem__SWIG_3(long jarg1, salTopicId jarg1_, long jarg2, long jarg3);
  public final static native long salTopicId_getItem__SWIG_4(long jarg1, salTopicId jarg1_, long jarg2, long jarg3);
  public final static native long salTopicId_getItem__SWIG_5(long jarg1, salTopicId jarg1_, long jarg2, long jarg3);
  public final static native long salTopicId_getItem__SWIG_6(long jarg1, salTopicId jarg1_, long jarg2, long jarg3, long jarg4);
  public final static native long salTopicId_getItem__SWIG_7(long jarg1, salTopicId jarg1_, long jarg2, long jarg3, long jarg4);
  public final static native long salTopicId_getItem__SWIG_8(long jarg1, salTopicId jarg1_, long jarg2, long jarg3, long jarg4);
  public final static native long salTopicId_getItem__SWIG_9(long jarg1, salTopicId jarg1_, long jarg2, long jarg3, long jarg4);
  public final static native long salTopicId_getItem__SWIG_10(long jarg1, salTopicId jarg1_, long jarg2, long jarg3, long jarg4);
  public final static native long salTopicId_getItem__SWIG_11(long jarg1, salTopicId jarg1_, long jarg2, long jarg3, long jarg4);
  public final static native long salTopicId_getItemStr(long jarg1, salTopicId jarg1_, long jarg2, long jarg3);
  public final static native long salTopicId_setItem__SWIG_0(long jarg1, salTopicId jarg1_, long jarg2, long jarg3);
  public final static native long salTopicId_setItem__SWIG_1(long jarg1, salTopicId jarg1_, long jarg2, long jarg3);
  public final static native long salTopicId_setItem__SWIG_2(long jarg1, salTopicId jarg1_, long jarg2, long jarg3);
  public final static native long salTopicId_setItem__SWIG_3(long jarg1, salTopicId jarg1_, long jarg2, long jarg3);
  public final static native long salTopicId_setItem__SWIG_4(long jarg1, salTopicId jarg1_, long jarg2, long jarg3);
  public final static native long salTopicId_setItem__SWIG_5(long jarg1, salTopicId jarg1_, long jarg2, long jarg3);
  public final static native long salTopicId_setItem__SWIG_6(long jarg1, salTopicId jarg1_, long jarg2, long jarg3, long jarg4);
  public final static native long salTopicId_setItem__SWIG_7(long jarg1, salTopicId jarg1_, long jarg2, long jarg3, long jarg4);
  public final static native long salTopicId_setItem__SWIG_8(long jarg1, salTopicId jarg1_, long jarg2, long jarg3, long jarg4);
  public final static native long salTopicId_setItem__SWIG_9(long jarg1, salTopicId jarg1_, long jarg2, long jarg3, long jarg4);
  public final static native long salTopicId_setItem__SWIG_10(long jarg1, salTopicId jarg1_, long jarg2, long jarg3, long jarg4);
  public final static native long salTopicId_setItem__SWIG_11(long jarg1, salTopicId jarg1_, long jarg2, long jarg3, long jarg4);
  public final static native long salTopicId_setItemStr(long jarg1, salTopicId jarg1_, long jarg2, long jarg3);
  public final static native long salTopicId_getProperty(long jarg1, salTopicId jarg1_, long jarg2, long jarg3);
  public final static native long salTopicId_setProperty(long jarg1, salTopicId jarg1_, long jarg2, long jarg3);
  public final static native void salTopicId_m_TopicId_shmid_set(long jarg1, salTopicId jarg1_, int jarg2);
  public final static native int salTopicId_m_TopicId_shmid_get(long jarg1, salTopicId jarg1_);
  public final static native void salTopicId_m_shmMapper_set(long jarg1);
  public final static native long salTopicId_m_shmMapper_get();
}
