/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class SWIGTYPE_p_svcDBL {
  private long swigCPtr;

  protected SWIGTYPE_p_svcDBL(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_svcDBL() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_svcDBL obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

