struct camera_SDS_TCM {
  string<32> private_revCode;  //private
  double     private_sndStamp; //private
  double     private_rcvStamp; //private
  long       private_seqNum;   //private
  long       private_origin;   //private
  long	Timing_parameter[10];	// 0.054 | none | Timing parameters[ | none | Science and corner rafts | 630 | 1,471,135  | 5,884,541 
  unsigned short	REB_ID;	// 0.054 | none | Raft Electronics Board ID | none | Cryostat
};
#pragma keylist camera_SDS_TCM 
