/*
 * Please so not edit this file by hand!
 * This file was automatically generated by: nddsgen
 */

#include <rpc/types.h>
#include <rpc/xdr.h>
#include "reset.h"


bool_t
xdr_resetStruct(XDR *xdrs, resetStruct *objp)
{
	if (!xdr_char(xdrs, &objp->resetFlag)) {
		return (FALSE);
	}
	return (TRUE);
}


