/*
 * Please so not edit this file by hand!
 * This file was automatically generated by: nddsgen
 */

#include <rpc/types.h>
#include <rpc/xdr.h>
#include "stop.h"


bool_t
xdr_stopStruct(XDR *xdrs, stopStruct *objp)
{
	if (!xdr_char(xdrs, &objp->stopFlag)) {
		return (FALSE);
	}
	return (TRUE);
}


