/*
 * Please so not edit this file by hand!
 * This file was automatically generated by: nddsgen
 */

#include <rpc/types.h>
#include <rpc/xdr.h>
#include "dbNotify.h"


bool_t
xdr_dbNotifyStruct(XDR *xdrs, dbNotifyStruct *objp)
{
	if (!xdr_int(xdrs, &objp->targetID)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->fieldName)) {
		return (FALSE);
	}
	return (TRUE);
}


