/*
 * Please so not edit this file by hand!
 * This file was automatically generated by: nddsgen
 */

#include <rpc/types.h>
#include <rpc/xdr.h>
#include "dbRecordReply.h"


bool_t
xdr_dbRecordReplyStruct(XDR *xdrs, dbRecordReplyStruct *objp)
{
	if (!xdr_int(xdrs, &objp->replyStatus)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->replyDestination)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->targetID)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->GPS_Position, 3, sizeof(float), xdr_float)) {
		return (FALSE);
	}
	if (!xdr_char(xdrs, &objp->currentlyTracked)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->templateImage, 128, sizeof(char), xdr_char)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->hiResImage, 128, sizeof(char), xdr_char)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->metalDetectorData, 128, sizeof(char), xdr_char)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->magnetometerData, 128, sizeof(char), xdr_char)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->radarData, 128, sizeof(char), xdr_char)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->classifierOutputData, 128, sizeof(char), xdr_char)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->spectrometerData, 128, sizeof(char), xdr_char)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->spectralFeaturesData, 128, sizeof(char), xdr_char)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->hiResImageTargetCoord, 2, sizeof(int), xdr_int)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->hiResImageScalingFactor, 2, sizeof(float), xdr_float)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->objSize)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->objColor)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->objTexture)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->objSpectralFeatures)) {
		return (FALSE);
	}
	if (!xdr_float(xdrs, &objp->classRisk)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->classEstInfoGain, 5, sizeof(float), xdr_float)) {
		return (FALSE);
	}
	if (!xdr_char(xdrs, &objp->classActive)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->classMemberProb, 128, sizeof(float), xdr_float)) {
		return (FALSE);
	}
	return (TRUE);
}


